### ISSUE TITLE
Are there plans(or How) to use existing instances on Aliyun

### ISSUE THREAD

**Issue by huang12zheng** [cnrancher/autok3s#140]
I have a instance A in aliyun. I create cluster with --provider = native
the answer as follow
```bash
[native] choose ssh node to connect: 
 	
  - xxIP: xxIP (master)

[choose one id]: xxIP
```
But I just want to make nodeId is following with aliyun. not IP

**Comment by Jason-ZW** [comment]
@huang12zheng If initializing K3s in `Aliyun ECS`, we suggest using `alibaba` provider. The `native` provider does not use any Cloud SDK, so `instanceID` cannot be obtained.

**Comment by huang12zheng** [comment]
@Jason-ZW
Is there an example?
The only API I can think of is createInstance,which I have read the source code.
And Aliyun's provider must create a metering ECS.There is no logic to reuse
I guess it doesn't have this feature yet?

**Comment by Jason-ZW** [comment]
@huang12zheng 
```
autok3s -d create --provider alibaba --region cn-hangzhou --name xxx --key-pair <your key-pair name> --v-switch <your v-switch id> --security-group <your security-group id> --ssh-key-path <your private key path> --master 1 --worker 1 --registries="https://fogjl973.mirror.aliyuncs.com" --access-key <your access-key> --access-secret <your access-secret>
```

more details: you can follow the documents [here](https://github.com/cnrancher/autok3s/blob/master/docs/alibaba/README.md)

**Comment by NewGr8Player** [comment]
@huang12zheng , it's no feature of reusing instances for now. As a temporary workaround, you can edit the file `$HOME/.autok3s/.status`. Edit field `instance-id` as  the nodeId on Aliyun.
But before resuing with native provider, please make sure that you have uninstall the k3s complete(or run `autok3s delete` successfully).

**Comment by huang12zheng** [comment]
@NewGr8Player 
I think what you're saying is file .state. not .status


> But before resuing with native provider, please make sure that you have uninstall the k3s complete(or run `autok3s delete` successfully).

I don't get what you mean.
If I input `autok3s delete`, cluster would delete if  there's only one Node.  And `.status` would be no infomation.

**Comment by huang12zheng** [comment]
@NewGr8Player @Jason-ZW 
Any plan about feature of reusing instances?

**Comment by Jason-ZW** [comment]
@huang12zheng There is no plan at present
