### ISSUE TITLE
Simplify command-line arguments

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#143]
## Scenario 1: The user did not provide the corresponding flags 
1. Check to see if there are default required resources. e.g.(vpc, v-switch, security-group, key-pair, ssh-key-path, region)
2. Create if it doesn't exist. e.g.(tag with autok3s)

## Scenario 2: The user-provided the corresponding flags 
1. just use the flags which the user-provided.

Also, need to update README.md

**Comment by kingsd041** [comment]
Confirmed issue. This is now working as expected per the comments here and the PR
