### ISSUE TITLE
请问有没有，离线安装k3s的说明？

### ISSUE THREAD

**Issue by chenmins** [cnrancher/autok3s#158]
众所周知的原因，
本地方式安装，经常拉不下来 基础镜像。

有没有 脱网环境下，利用自己架设的harbor的 autok3s的说明，非常感谢

`
autok3s create \
    --provider native \
    --name k3s \
    --ssh-key-path default.pem \
    --master-ips 10.0.16.26 \
    --worker-ips 10.0.16.27,10.0.16.28
`

**Comment by JacieChao** [comment]
可以通过传入`--registries` 参数来指定私有镜像仓库地址，例如
```
autok3s create  --provider native  --name k3s --registries=https://<registry1>,https://<registry2> ...
```

**Comment by chenmins** [comment]
> 可以通过传入`--registries` 参数来指定私有镜像仓库地址，例如
> 
> ```
> autok3s create  --provider native  --name k3s --registries=https://<registry1>,https://<registry2> ...
> ```

还有，如果 私服需要认证，以及信任 自定义生成的证书的参数，请问怎么写？谢谢。

**Comment by Jason-ZW** [comment]
@chenmins 目前还不支持需要认证的私有镜像仓库，后续会支持

**Comment by Jason-ZW** [comment]
在#162中记录，关闭此issue
