### ISSUE TITLE
Delete native K3s, did not judge the return value of uninstalling k3s

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#169]
**Autok3s version:**
```
Version: {"gitVersion":"v0.3.0-rc1","gitCommit":"4b82f5e5114e234da010e07e755b532e31c94bc9","gitTreeState":"","buildDate":"2020-12-15T06:16:35Z","goVersion":"go1.13.12","compiler":"gc","platform":"darwin/amd64"}
```

**Steps to reproduce: **
1. Use autok3s to start the k3s cluster, and wait for the K3s cluster to start successfully
```
autok3s create --debug \
    --provider native \
    --name native-1 \
    --ssh-user ubuntu \
    --ssh-key-path ~/.ssh/id_rsa \
    --master-ips 192.168.64.33 \
    --worker-ips 192.168.64.34
```
2. ssh to `192.168.64.33` and `192.168.64.34` respectively to delete the corresponding uninstall K3s script

3. Delete k3s cluster through autok3s
```
 ksd@Ksd  ~/.autok3s  autok3s delete \
    --provider native \
    --name native-1 -d
[native] are you sure to delete cluster native-1 [y/n]: y
INFO[0001] [native] executing delete cluster logic...
INFO[0002] [native] successfully excuted delete cluster logic
```
**Result:**
The k3s uninstall script has been deleted in my k3s environment. Normally, it should report an error and prompt that the deletion of k3s failed.

**Comment by Jason-ZW** [comment]
`native` provider has been refactored, so this issue is invalid.

**Comment by kingsd041** [comment]
I need to verify this issue in the new version after refactoring

**Comment by kingsd041** [comment]
native provider has been refactored, so this issue is invalid.
