### ISSUE TITLE
[Enhancement] CNI Installer Image Need Support arm/arm64/amd64

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#17]
CNI Installer Image `zhenyangzhao/cni-installer:v0.8.6` Need Support `arm/arm64/amd64`

## Related:
https://github.com/Jason-ZW/cni-installer

**Comment by orangedeng** [comment]
Do we still need this in a newer k3s version?

**Comment by orangedeng** [comment]
As we remove terway cni, we don't need this any more.
