### ISSUE TITLE
When deleting a cluster that does not exist, you should first prompt that the cluster does not exist

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#191]
When deleting a cluster that does not exist, you should first prompt that the cluster does not exist

```
 ksd@Ksd  ~/Downloads  autok3s list
  NAME  REGION  PROVIDER  STATUS  MASTERS  WORKERS

 ksd@Ksd  ~/Downloads  autok3s delete --provider native --name native-1
[native] are you sure to delete cluster native-1 [y/n]: y
INFO[0008] [native] executing delete cluster logic...
FATA[0008] [cluster] was not found in the .state file
```

**Comment by Jason-ZW** [comment]
`native` provider has been refactored, so this issue is invalid.

**Comment by kingsd041** [comment]
I need to verify this issue in the new version after refactoring

**Comment by kingsd041** [comment]
Similar problems exist in Alibaba or Tencent providers and need to be resolved

**Comment by JacieChao** [comment]
I think it's not a big deal to confirm first or check cluster exist first.
