### ISSUE TITLE
Should not be allowed adding clusters of the same name

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#193]
**Autok3s version:**
```
Version: {"gitVersion":"master","gitCommit":"30fbc75d8a3b26d05b0921264e0c6a9f75b97b32","gitTreeState":"","buildDate":"2020-12-15T06:16:35Z","goVersion":"go1.13.12","compiler":"gc","platform":"darwin/amd64"}
```

**Steps to reproduce: **
1. Use autok3s to add a cluster named `native-1`,
```
autok3s create \
    --provider native \
    --name native-1 \
    --ssh-user ubuntu \
    --ssh-key-path ~/.ssh/id_rsa \
    --master-ips 192.168.64.33

autok3s kubectl get nodes
NAME        STATUS     ROLES         AGE   VERSION
autok3s-1   NotReady   etcd,master   5s    v1.19.5+k3s2
```

2. Using other nodes, use autok3s again to add a cluster named `native-1`
```
autok3s create \
    --provider native \
    --name native-1 \
    --ssh-user ubuntu \
    --ssh-key-path ~/.ssh/id_rsa \
    --master-ips 192.168.64.34

autok3s kubectl get nodes
NAME        STATUS   ROLES         AGE   VERSION
autok3s-2   Ready    etcd,master   20s   v1.19.5+k3s2
```

**Result:**
When repeatedly adding clusters with the same name, the second cluster should not be added successfully

**Comment by Jason-ZW** [comment]
1. Check if the `.state` file contains a cluster of the same name.
2. Check if the node has running the k3s process.

**Comment by Jason-ZW** [comment]
`native` provider has been refactored, so this issue is invalid.

**Comment by kingsd041** [comment]
I need to verify this issue in the new version after refactoring

**Comment by kingsd041** [comment]
native provider has been refactored, so this issue is invalid.
