### ISSUE TITLE
Installing a single-node K3S cluster should not take the "--cluster-init" parameter

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#208]
Version: {"gitVersion":"v0.3.0-rc2","gitCommit":"3d01ce9dcb3c5cd6594b0dc6aa1dcfe7bb78b29f","gitTreeState":"","buildDate":"2020-12-25T02:01:30Z","goVersion":"go1.13.12","compiler":"gc","platform":"darwin/amd64"}

Use autok3s to create a single-node master cluster
```

autok3s -d create -p alibaba --name myk3s4 --master 1
```
During the installation process, you will see the following log:
```
DEBU[0074] [cluster] k3s master command: curl -sLS http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_TOKEN='a0e6eee6bd98ad785e6c520f5b7a6d8c' INSTALL_K3S_EXEC='server --cluster-init --tls-san 112.124.105.219 --node-external-ip 112.124.105.219 ' INSTALL_K3S_CHANNEL='stable' sh -
```

If you are installing a single-node k3s cluster, you should not use the parameter `--cluster-init`, this parameter is only used in "High Availability with Embedded DB"

reference:
https://rancher.com/docs/k3s/latest/en/installation/ha-embedded/

**Comment by JacieChao** [comment]
We will add a new param `--cluster` when create cluster using `autok3s`. If you're going to create HA mode of k3s cluster with embedded DB, please use the command `autok3s create -p alibaba -n myk3s --master 3 --cluster`

**Comment by kingsd041** [comment]
```
# autok3s -d create -p alibaba --name myk3s4 --master 1
curl -sLS http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_TOKEN='912c2fc422e80436aacaef71af5fe1fa' INSTALL_K3S_EXEC='server --tls-san 47.96.66.160 --node-external-ip 47.96.66.160 ' INSTALL_K3S_CHANNEL='stable' sh -...
```
