### ISSUE TITLE
Cannot log in after enabling ui

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#211]
Version: {"gitVersion":"v0.3.0-rc2","gitCommit":"3d01ce9dcb3c5cd6594b0dc6aa1dcfe7bb78b29f","gitTreeState":"","buildDate":"2020-12-25T02:01:30Z","goVersion":"go1.13.12","compiler":"gc","platform":"darwin/amd64"}

1. Use `--ui` parameter to start K3s cluster
```
autok3s -d create -p alibaba --name myk3s3 --master 1 --worker 1 --ui --region cn-beijing --zone cn-beijing-h
```
2. Wait for the cluster to start successfully, follow the prompts to access the dashboard through the browser

3. Create token with reference to https://github.com/kubernetes/dashboard/blob/master/docs/user/access-control/creating-sample-user.md

Cannot log in to dashboard with token:
![image](https://user-images.githubusercontent.com/19684717/103327433-82ca3200-4a8f-11eb-9ab0-f2bfee7ceedb.png)

This may be related to the dashboard version

**Comment by JacieChao** [comment]
The dashboard version is too old to support the current stable version of k3s cluster. Will upgrade to dashboard v2.0.5

**Comment by kingsd041** [comment]
Test passed.
The dashboard has been upgraded to `kubernetesui/dashboard:v2.0.5`
