### ISSUE TITLE
[Tencent] The default disk size should be modified to `50G`

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#214]
Version: {"gitVersion":"v0.3.0-rc3","gitCommit":"78d27cd25a72dfc5f0d5c68ae06dfabd69fc4f76","gitTreeState":"","buildDate":"2020-12-31T01:39:28Z","goVersion":"go1.13.12","compiler":"gc","platform":"darwin/amd64"}

** Provider:** 
Tencent

Autok3s creates a Tencent provider k3s cluster. The default disk size is `60G`, which should be changed to `50G`. Because the default disk size when creating an instance from Tencent Cloud Platform is `50G`

```
autok3s -d create -p tencent --help
--disk-size string                    Used to specify the system disk size used by the instance (default "60")
```

![image](https://user-images.githubusercontent.com/19684717/103391745-e7e85b00-4b55-11eb-8d2b-b3157ddaa47d.png)

**Comment by JacieChao** [comment]
已修改
![image](https://user-images.githubusercontent.com/23305062/103403777-53e5b600-4b8c-11eb-9b28-f0631dbf26fe.png)
