### ISSUE TITLE
Tencent providers should use EIP

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#218]
autok3s version
Version: {"gitVersion":"v0.3.0-rc3","gitCommit":"78d27cd25a72dfc5f0d5c68ae06dfabd69fc4f76","gitTreeState":"","buildDate":"2020-12-31T01:39:28Z","goVersion":"go1.13.12","compiler":"gc","platform":"darwin/amd64"}

If you shut down the instance from Tencent Cloud, the public IP will change, so you need to use EIP by default

![image](https://user-images.githubusercontent.com/19684717/103614254-2077a280-4f63-11eb-8802-f6ab25f8d989.png)

**Comment by JacieChao** [comment]
autok3s removed `start/stop` command which means we DO NOT SUPPORT manage instance using EIP by default.
