### ISSUE TITLE
怎么指定安装的具体版本，或者 支持离线安装 ？

### ISSUE THREAD

**Issue by ssuhvs** [cnrancher/autok3s#241]
1、怎么指定安装的具体版本
2、怎么支持离线安装

**Comment by JacieChao** [comment]
1. 安装指定版本的k3s集群，可以通过指定`--k3s-version` 参数，例如 `autok3s create -p alibaba --name myk3s --k3s-version v1.19.7+k3s1 --master 1`
2. 目前版本仅支持配置私有镜像仓库，可以通过指定`--registry`参数，具体可参见[配置私有镜像仓库文档](https://github.com/cnrancher/autok3s/tree/master/docs/i18n/zh_cn/alibaba#%E9%85%8D%E7%BD%AE%E7%A7%81%E6%9C%89%E9%95%9C%E5%83%8F%E4%BB%93%E5%BA%93)，后续版本会支持离线安装k3s binary

更多详细的参数信息可以通过 `autok3s --help`来查看
