### ISSUE TITLE
[Feature Request] Support K3s upgrade

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#262]
Need to support upgrade K3s cluster, e.g. `autok3s --provider xxx upgrade --name xxx --k3s-version xxxx `

**Comment by ly5156** [comment]
UI demo:
<img width="1139" alt="image" src="https://user-images.githubusercontent.com/3406205/168747730-19f382dd-7c18-45f6-93e8-dea8fc0da120.png">
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/3406205/168747864-14373db7-3335-465c-a7cd-9af15234f842.png">
