### ISSUE TITLE
[Enhancement] UI components needs to query the correlation information from the CloudProviders’ SDK

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#263]

**Comment by JacieChao** [comment]
Add aws/harvester SDK for v0.5.0
Add aliyun/GCE/tencent SDK for v0.5.1

**Comment by ly5156** [comment]
由于 google gce api 关键字查询，有以下问题，决定查询镜像时去掉关键字搜索功能
1. 有时会返回空结果，比如搜索关键字，如果全是数字，比如搜索ubutun  2004 版，关键字：2004，api 响应是空
2. 如果存在关键字搜索，api 不支持按时间排序
3. 调用 api 时，无法通过传参过滤掉不建议使用的镜像，导致响应结果太多

目前选择镜像 modal：
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/3406205/197435841-384b12ab-55be-4ab6-8a4e-8f1d5716fc77.png">
<img width="866" alt="image" src="https://user-images.githubusercontent.com/3406205/197435855-96f078c5-6019-47ce-aede-1ada51b366f4.png">
