### ISSUE TITLE
[BUG] Disable form password saving

### ISSUE THREAD

**Issue by niusmallnan** [cnrancher/autok3s#264]
保存模板时，经常触发浏览器的密码保存行为，这些保存行为是无意义的。
是否和表单的一些前段属性有关，诱导了浏览器的这种行为？

<img width="456" alt="屏幕快照 2021-03-24 上午11 07 53" src="https://user-images.githubusercontent.com/998984/112248837-9a314980-8c91-11eb-8be0-92b8c08a30f8.png">

浏览器：Chrome
OS：Mac OSX
版本：v0.4.0

**Comment by ly5156** [comment]
在chrome里，设置->自动填充/密码->提示保存密码 选项 置灰就可以了
![image](https://user-images.githubusercontent.com/3406205/118790107-0ada9800-b8c8-11eb-82ca-ba1d658b31e7.png)

**Comment by ly5156** [comment]
通过修改 input 的字体为 dot 字体来解决浏览器提示保存密码问题，因为页面里没有 password 类型的 input，所以浏览器不会提示保存密码
