### ISSUE TITLE
[Enhancement] K3s options form experience

### ISSUE THREAD

**Issue by niusmallnan** [cnrancher/autok3s#267]
对于Create Cluster的K3s options表单，虽然提供了Extra Args的通用体验，但是一些常用的参数，最好可以友好的形式辅助用户填写，比如：
1. channel：对应的值基本是固定的，直接做成可选的下拉菜单，可以考虑用Rancher UI里面那种可以额外填写自定义内容的下拉菜单控件
2. runtime：Containerd和Docker两个选项，默认为Containerd，用户可切换为Docker，并提示AutoK3s会为用户安装Docker。
2. disable（组件禁用）：可以让用户很方便禁用coredns, servicelb, traefik,local-storage, metrics-server等
3. flannel-backend：可以方便用户选择‘none’, ‘vxlan’, ‘ipsec’, ‘host-gw’, or ‘wireguard’等

以上参数，用户交互填写后，都在Extra Args中自动附加参数，以展示参数传递的细节。

版本：v0.4.0

**Comment by ly5156** [comment]
对应样式设计
![image](https://user-images.githubusercontent.com/3406205/112961837-526e5e80-9178-11eb-9e39-d1775a067b6f.png)

**Comment by Jason-ZW** [comment]
worker-extra-args 选择后并没有填充到表单

![image](https://user-images.githubusercontent.com/36479205/113500360-e44ae280-954f-11eb-9abf-2c5194639158.png)

**Comment by JacieChao** [comment]
@Jason-ZW  Only `docker` runtime needs to set the extra-args option.
