### ISSUE TITLE
[Enhancement] Custom quick-start startup parameters

### ISSUE THREAD

**Issue by niusmallnan** [cnrancher/autok3s#268]
目前，quick-start只能允许内置默认的AWS相关参数来运行。建议quick-start作为一种模板，用户可以调整编辑，这样利用率更高。

版本：v0.4.0

**Comment by ly5156** [comment]
quick-start 页面增加了alibaba provider 和 tencent provider选项

**Comment by niusmallnan** [comment]
@Jason-ZW 
I don't think this issue has been addressed.
I still cannot edit the default `quick-start` params as a  built-in template.

**Comment by JacieChao** [comment]
For current version, create a new template will use build-in default template. Will enhance it at next version.

**Comment by ly5156** [comment]
![quick-start](https://user-images.githubusercontent.com/3406205/210289063-63f4400d-fa56-45e2-840d-1dbf7af9b493.gif)

**Comment by JacieChao** [comment]
Implement `default_template` for providers instead of hard code variables. The `default_template` will update to the latest best-practice instance options for each provider before each Release.
