### ISSUE TITLE
[Feature Request] Highlight the cluster bootstrap commands in UI

### ISSUE THREAD

**Issue by niusmallnan** [cnrancher/autok3s#276]
Although in the UI console logs, we can capture the autok3s commands, so we can understand what commands are used to create k3s.

It is better that we can copy the bootstrap commands of a k3s cluster from a button in the UI.
This is very meaningful for understanding CLI usage and troubleshooting.

**Comment by ly5156** [comment]
UI 设计：
![image](https://user-images.githubusercontent.com/3406205/113681617-bfdc3b00-96f4-11eb-8fed-6074a46693ad.png)

**Comment by ly5156** [comment]
UI 设计
![image](https://user-images.githubusercontent.com/3406205/113687136-9b835d00-96fa-11eb-9f26-c1c5b15e6005.png)
