### ISSUE TITLE
[Feature Request] Support upgrading when using local container mode

### ISSUE THREAD

**Issue by niusmallnan** [cnrancher/autok3s#288]
**Is your feature request related to a problem? Please describe.**
I previously installed autok3s 0.4.0 using local container mode. I configured templates and keys. I want to keep these settings when I upgrade to the new version.

**Describe the solution you'd like**
Maybe we can use `docker run --volumes-from xxx` to support this feature. However, the `sqlite-db` file is not in the predefined container volume.

I use this way as the workaround:
```
docker cp <old-container>:/root/.autok3s/.db/autok3s.db .
docker rm -f <old-container>
docker run -itd --restart=unless-stopped -p 8080:8080 cnrancher/autok3s:v0.4.1-rc1
docker cp autok3s.db <new-container>:/root/.autok3s/.db/autok3s.db
docker restart <new-container>
```

**Comment by JacieChao** [comment]
Need to merge DB file for CLI too.
https://github.com/cnrancher/autok3s/issues/261

**Comment by JacieChao** [comment]
Upgrade from v0.4.0:
```
docker cp <old-container>:/root/.autok3s .
docker rm -f <old-container>
docker run -itd --restart=unless-stopped -p 8080:8080 -v $PWD/.autok3s:/root/.autok3s cnrancher/autok3s:v0.4.1
```

Upgrade from v0.4.1 to higher
```
docker run -itd --restart=unless-stopped -p 8080:8080 --volumes-from <old-container> cnrancher/autok3s:v0.4.x
```
