### ISSUE TITLE
Tencent RAM policy create failed

### ISSUE THREAD

**Issue by zengzhengrong** [cnrancher/autok3s#289]
I follow https://docs.rancher.cn/docs/k3s/autok3s/tencent/_index to create a RAM policy ， But meet with ```service not found```, see below

![image](https://user-images.githubusercontent.com/23110784/113564356-d6728b80-963b-11eb-883d-a43ac87be56f.png)

**Comment by JacieChao** [comment]
`ccs` is part of TKE service permission. If you want to use Tencent Cloud Provider, you will need to create a new cluster router for it. 
If you don't need tencent CCM, this part of policy is no need for you.
