### ISSUE TITLE
[Feature Request] Allow set k3s-install-script from UI

### ISSUE THREAD

**Issue by JacieChao** [cnrancher/autok3s#294]
**Is your feature request related to a problem? Please describe.**
When I use native provider to deploy k3s locally, I can't set k3s-install-script that I have mirrored from github which result a very slow installation.

**Describe the solution you'd like**
In `K3s Options` tab, add `k3s-install-script` params.

**Comment by JacieChao** [comment]
k3s-install-script 做成下拉框选择的形式，内容如下：
https://get.k3s.io
http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh

**Comment by ly5156** [comment]
### UI 样式
1. 初始状态：
![image](https://user-images.githubusercontent.com/3406205/113979551-f9897f00-9877-11eb-9f6d-a1fd4743f5df.png)

2. 展开状态
![image](https://user-images.githubusercontent.com/3406205/113979642-1625b700-9878-11eb-9c4a-cba662582880.png)
