### ISSUE TITLE
[BUG] UI fail save K3s options when edit template again

### ISSUE THREAD

**Issue by zengzhengrong** [cnrancher/autok3s#296]
![image](https://user-images.githubusercontent.com/23110784/114294705-f2aa7880-9ad2-11eb-8cd7-ca6288f8ee5b.png)

When I edit again

![image](https://user-images.githubusercontent.com/23110784/114294725-18378200-9ad3-11eb-8e07-023c4d53c980.png)

**Comment by ly5156** [comment]
@zengzhengrong 
1. `Master Extra Args` -> runtime `containerd`：

*  默认就是 `contianerd`, 保存时不会在 `Master Extra Args`属性里带任何信息，所以再次编辑时，右侧`Used Options`部分不显示，是正常的；
* 左侧`Available Options` 是可选项，每次显示，都会是初始状态，不会跟当前模板内容有任何联动效果

**Comment by ly5156** [comment]
@zengzhengrong 感谢反馈和支持
1. Native provider template， registry 有值时编辑模板，首次显示为空，focus 后才显示，确认是bug，会在下一个版本修正

**Comment by JacieChao** [comment]
tested with v0.4.2-rc1.
