### ISSUE TITLE
[BUG] Cannot change Region and Zone

### ISSUE THREAD

**Issue by gyliu513** [cnrancher/autok3s#299]
![image](https://user-images.githubusercontent.com/4461983/114560426-45389000-9c9f-11eb-8ec6-ecf8ea4a1a5d.png)

**Comment by JacieChao** [comment]
Quick start is not available to change default region and zone for current version. You can use `Advance` to change the default region and zone.

**Comment by JacieChao** [comment]
If you want to change the default template for Quick Start, please use the `cluster template` which is under the `Settings` menu. Then set the template as the default one. 
Please let us know if you still have other problems. Thanks.
