### ISSUE TITLE
[Feature Request] Support K3d provider

### ISSUE THREAD

**Issue by JacieChao** [cnrancher/autok3s#303]

**Comment by ly5156** [comment]
### UI 样式：
1. Instance Options
![image](https://user-images.githubusercontent.com/3406205/115523758-f81c7580-a2bf-11eb-9617-538b1dfcbebb.png)

2. K3s Options
![image](https://user-images.githubusercontent.com/3406205/115523849-17b39e00-a2c0-11eb-8de6-0efe4f3ea861.png)

3. Additional Options
![image](https://user-images.githubusercontent.com/3406205/115523960-331ea900-a2c0-11eb-9ef1-bbd489517644.png)

**Comment by ly5156** [comment]
新的表单布局：
![image](https://user-images.githubusercontent.com/3406205/116491593-d24d2d00-a8cc-11eb-94b3-15fc93bbe31b.png)
高级展开部分
![image](https://user-images.githubusercontent.com/3406205/116491655-f6107300-a8cc-11eb-95b6-2c8411d4ae22.png)

**Comment by JacieChao** [comment]
@Jason-ZW also need to add docs for `k3d` provider

**Comment by Jason-ZW** [comment]
Will add k3d documents when releasing the RC version.

> @Jason-ZW also need to add docs for `k3d` provider
