### ISSUE TITLE
[Feature Request] Native created cluster didn't show up on the list

### ISSUE THREAD

**Issue by haroldrandom** [cnrancher/autok3s#330]
**Describe the bug**
As the title said.

**To reproduce**
1. start the Autok3s with docker
2. Create a native k3s cluster with 1 master, 1 node
2. after it succeeds, return to the portal, and hit fresh
3. nothing shows up.

**Expected behavior**
the cluster show up in the list.

**Screenshots**
![image](https://user-images.githubusercontent.com/14357159/120666232-0238b300-c4bf-11eb-9e25-2a743cc421ab.png)

**Environments (please complete the following information):**
 - OS: Windows 10
 - AutoK3s Version: v0.4.0

**Additional context**

**Comment by JacieChao** [comment]
`native` provider does not support `list/delete/describe/ssh` command, but you can use kubectl to manage resources for K3s.
http://docs.rancher.cn/docs/k3s/autok3s/native/_index/#%E9%9B%86%E7%BE%A4%E7%AE%A1%E7%90%86

**Comment by haroldrandom** [comment]
Emmm. okay, understood.

But will it be supported in the feature? 
It seems strange that the cluster didn't show and a bug maybe in the eye of someone who didn't read the doc carefully.

**Comment by JacieChao** [comment]
Yeah, we'll consider how to support the `native` provider better in the future. 
For now, the `native` provider is just help to install/join nodes for users who don't have any Cloud provider that we have supported, and will not manage instances that are not handled by AutoK3s.

**Comment by haroldrandom** [comment]
Cool, feel free to close it if there is a PR related to this to be merged
