### ISSUE TITLE
[Feature Request] Autok3s web address pops up automatically

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#340]
**Is your feature request related to a problem? Please describe.**

When starting the local UI, it is recommended to automatically pop up the Autok3s web address from the browser
```
 ksd@ksd  ~  autok3s serve
INFO[0000] run as daemon, listening on 127.0.0.1:8080
```

![image](https://user-images.githubusercontent.com/19684717/127596917-90cbff78-01b8-4907-9791-8dc855924403.png)

**Comment by JacieChao** [comment]
Close issue. Tested with v0.8.0-rc1. AutoK3s can automatically pop up the web address from the browser.
