### ISSUE TITLE
[Feature Request] Mac m1 silicon support

### ISSUE THREAD

**Issue by llqgit** [cnrancher/autok3s#344]
When I install autok3s as the official website do in my new macbook pro with M1.
It could not found and download file `autok3s_darwin_arm64`
And then an error xml appeared in my dir `/usr/local/bin/autok3s`, content like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>610FD13B998B3E39366EF3F1</RequestId>
  <HostId>rancher-mirror.cnrancher.com</HostId>
  <Key>autok3s/v0.4.3/autok3s_darwin_arm64</Key>
</Error>
```

**Comment by JacieChao** [comment]
@llqgit Thanks for your report. How did you install AutoK3s? Using the install command below?

```
curl -sS http://rancher-mirror.cnrancher.com/autok3s/install.sh  | sh
```

**Comment by JacieChao** [comment]
@llqgit There's something wrong with our mirror when sync with the Github release, please try again. 
Thanks!

**Comment by llqgit** [comment]
I have tried `curl -sS http://rancher-mirror.cnrancher.com/autok3s/install.sh  | INSTALL_AUTOK3S_MIRROR=cn sh` of cause and still not work now,  with return a xml is the same as before.

**Comment by JacieChao** [comment]
It's very curious with the same error XML because AutoK3s has released `v0.4.4`. 
What about command as below:
```
curl -sS http://rancher-mirror.rancher.cn/autok3s/install.sh | INSTALL_AUTOK3S_MIRROR=cn sh
```

**Comment by llqgit** [comment]
It has changed to:
```sh
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>611133AFF15BB2383377569E</RequestId>
  <HostId>rancher-mirror.rancher.cn</HostId>
  <Key>autok3s/v0.4.4/autok3s_darwin_arm64</Key>
</Error>
```

I think the point is `darwin_arm64` arm64 with mac M1 cpu, not the version 0.4.4.

**Comment by JacieChao** [comment]
Sorry about the misunderstanding. AutoK3s is not supported `darwin_arm64` for now.

**Comment by llqgit** [comment]
I handle this problem by download and copy the `autok3s_darwin_amd64` as `autok3s` to the /usr/local/bin dir manually. And  it is worked for now.

**Comment by Jason-ZW** [comment]
Closed. If there are other problems please reopen.

**Comment by armenr** [comment]
For anyone who lands here and is looking for m1 Mac support + k3s ---> look into k3d.
