### ISSUE TITLE
[BUG] native provider failed to create cluster

### ISSUE THREAD

**Issue by gohopo** [cnrancher/autok3s#348]
**Describe the bug**
I create a cluster on 2 vms(vmware) with native provider,and get ssh timed out error.
```
time="2021-09-17T05:43:16-07:00" level=info msg="[native] executing create logic..."
time="2021-09-17T05:43:16-07:00" level=info msg="[native] executing init k3s cluster logic..."
time="2021-09-17T05:43:16-07:00" level=info msg="[native] creating k3s master-1..."
time="2021-09-17T05:43:16-07:00" level=info msg="[cluster] k3s master command: curl -sLS https://get.k3s.io | K3S_TOKEN='7c09bdd583027971eff4d461bdbcbb6f' INSTALL_K3S_EXEC='server --tls-san 192.168.1.239 --node-external-ip 192.168.1.239 --no-deploy traefik --cluster-cidr 10.42.0.0/16' INSTALL_K3S_CHANNEL='stable' sh -"
time="2021-09-17T05:45:16-07:00" level=error msg="[native] failed to create cluster: [ssh-dialer] init dialer [192.168.1.239:22] error: timed out waiting for the condition"
time="2021-09-17T05:45:16-07:00" level=info msg="[native] executing rollback logic..."
time="2021-09-17T05:45:16-07:00" level=info msg="[native] instances [192-168-1-239] will be rollback"
time="2021-09-17T05:47:16-07:00" level=warning msg="[native] failed to uninstall k3s on master node 192-168-1-239: [ssh-dialer] init dialer [192.168.1.239:22] error: timed out waiting for the condition"
time="2021-09-17T05:47:16-07:00" level=info msg="[native] successfully executed rollback logic"
```

**To reproduce**
1. open 2 vms on vmware,use `autok3s serve`,open web ui
2. use `native` provider create cluster

**Environments (please complete the following information):**
 - OS: Ubuntu 21.04
 - AutoK3s Version: v0.4.4

**Comment by JacieChao** [comment]
To create K3s cluster by `native` provider, please check the ssh user:
1. Please check whether you have correct the ssh login settings, e.g. change ssh user to correct? If your VM is using password you need to filling the password part.
2. If you are using nonroot user, you also need to config allow nonpassword for this user, AutoK3s will use sudo to run install script.

**Comment by gohopo** [comment]
@JacieChao
我开始用的oracle cloud的免费vps，也是报这个错误，才在本地用虚拟机尝试的。
我的vps在mobaxterm上可以用ssh密钥验证登录，使用相同的私钥设置在autok3s上就报超时.
在本地虚拟机上是用ssh密码创建集群的，可以ping通，但是还是报错`error: timed out waiting for the condition`

I started using the free vps with oracle cloud and also reported this error before I tried it locally with a virtual machine.
My vps can login with ssh key authentication on mobaxterm and timeout on autok3s with the same private key settings.
On the local VM I created the cluster with the ssh password and I can ping it, but it still reports an error`error: timed out waiting for the condition`
(DeepL Translator)

**Comment by JacieChao** [comment]
I just can tell the AutoK3s can't create ssh dialer to your VM from the error log. Would you please help me to ensure the following steps?

1. How did you start AutoK3s, using `CLI` or `docker run`? 
2. Where did you run AutoK3s, local PC or in VM? What OS is it? 
3. Could you please try `ssh -i <your-private-key> <ssh-user>@192.168.1.239` from the terminal where you have run AutoK3s?

**Comment by gohopo** [comment]
@JacieChao 
1. use `CLI`, `autok3s serve`
2. local PC in Vmware workstation, `ubuntu 21.04` OS
3. I'm at work now, waiting for me to try it at home tonight. Thanks for your help.

**Comment by gohopo** [comment]
I'm sorry, my ssh private key was in ppk format before, now I use PuTTYgen to convert to openSSH format and it works.
Autok3s is great, I hope it can support cluster list management afterwards, thanks!

**Comment by Jason-ZW** [comment]
@gohopo Native Provider support please follow #330

**Comment by JacieChao** [comment]
@gohopo Thanks for your reply, we will add more information in docs later.
