### ISSUE TITLE
[BUG] cluster created but not displayed in UI

### ISSUE THREAD

**Issue by han-ysys** [cnrancher/autok3s#353]
**Describe the bug**
A cluster was created with autok3s successfully but no cluster was shown in autok3s UI.
<img width="1792" alt="截屏2021-11-14 21 09 48" src="https://user-images.githubusercontent.com/70315648/141682419-9e6bcc3d-3604-41ee-ab17-20dea3c9d1a7.png">

**To reproduce**
[cluster] k3s master command: curl -sLS http://rancher-mirror.cnrancher.com/k3s/k3s-install.sh | INSTALL_K3S_MIRROR=cn K3S_TOKEN='1527938602b358b53a4adec5c85245e0' INSTALL_K3S_EXEC='server  --tls-san 10.254.253.44 --tls-san 10.254.253.53 --node-external-ip 10.254.253.44 --cluster-cidr 10.42.0.0/16 --cluster-init' INSTALL_K3S_CHANNEL='stable' sh -

on the node it says:
![截屏2021-11-14 21 10 51](https://user-images.githubusercontent.com/70315648/141682447-c0193d1c-59b1-4e34-b056-d2b1980016d5.png)

**Later I recreated a same cluster** 
[INFO]  Skipping /usr/local/bin/kubectl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/crictl symlink to k3s, already exists
[INFO]  Skipping /usr/local/bin/ctr symlink to k3s, command exists in PATH at /usr/bin/ctr
[INFO]  Creating killall script /usr/local/bin/k3s-killall.sh
[INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh
[INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service
[INFO]  systemd: Enabling k3s unit
[INFO]  systemd: Starting k3s

This time kubectl gives a TLS handshake timeout and still nothing in UI:
[root@k3sserver-4 ~]# autok3s kubectl config use-context test
Switched to context "test".
[root@k3sserver-4 ~]# autok3s kubectl get pods -A
Unable to connect to the server: net/http: TLS handshake timeout

**Environments (please complete the following information):**
 - AutoK3s Version [e.g. v0.4.0]
 - Same OS on four nodes: cat /proc/version
Linux version 3.10.0-1160.11.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Fri Dec 18 16:34:56 UTC 2020

**other k3s version**
I also tried 1.19.5 but failed with same problem

**Comment by JacieChao** [comment]
1. cluster created by `native` provider won't show up in the UI list for current version(https://github.com/cnrancher/autok3s/issues/330)
2. If you want to create cluster with the same node, please [uninstall k3s](https://rancher.com/docs/k3s/latest/en/installation/uninstall/) for each node

**Comment by han-ysys** [comment]
thanks for the quick reply!
k3s is uninstalled on all four nodes but I noticed that the deleted cluster option remains in the 'launch kubectl' selector.
Is there any thing to do with that?
<img width="566" alt="截屏2021-11-15 17 00 45" src="https://user-images.githubusercontent.com/70315648/141752650-c4273de5-9262-4500-beb5-e37a328426dc.png">

**Comment by JacieChao** [comment]
For now, there's nothing we can do, sorry :) But you can try to reinstall with the same name of your native cluster, then the kubeconfig file will update for the new cluster.
