### ISSUE TITLE
[Feature Request] 外网访问Autok3s UI

### ISSUE THREAD

**Issue by iemsoft** [cnrancher/autok3s#361]
使用 这种方式安装，监听的是127.0.0.1:8080,没办法外网访问，另外这个管理界面没有登陆验证机制。
curl -sS http://rancher-mirror.cnrancher.com/autok3s/install.sh  | INSTALL_AUTOK3S_MIRROR=cn sh

**Comment by JacieChao** [comment]
1. `autok3s serve` is listen on 127.0.0.1 by default, you can use `autok3s serve --bind-address 0.0.0.0 --bind-port 9999` to change the listen address and port.
2. AutoK3s is a small tool for developers, which can help auto-deploy K3s quickly, not an enterprise-level product. So there's no need to support login auth for now.

**Comment by Jason-ZW** [comment]
Please reopen this issue if you have other questions.
