### ISSUE TITLE
[Web UI] Clusters List is always empty

### ISSUE THREAD

**Issue by liangjihua** [cnrancher/autok3s#365]
**Describe the bug**
The clusters page does not display any created clusters, but the `launch kubectl dialog page` can select the created clusters
When I used the web ui to create a cluster, the console log did not show any errors in creating the cluster, and the pods on the master node were all running normally.
I am not sure whether it is not displayed in the UI because the cluster creation failed, or it is a bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/35123083/144972988-1545d37e-33ad-495f-aed0-620f83dc2fa8.png)

**Environments (please complete the following information):**
 - OS: dockerdesktop for windows
 - AutoK3s Version: v0.4.5

**Additional context**

Here is the last part of console log when I created a cluster:

[log](https://github.com/cnrancher/autok3s/files/7665793/tee.txt)

**Comment by JacieChao** [comment]
cluster created by native provider won't show up in the UI list for current version(https://github.com/cnrancher/autok3s/issues/330)

**Comment by JacieChao** [comment]
Refer https://github.com/cnrancher/autok3s/issues/330
