### ISSUE TITLE
[Feature Request] Support Deploy Rancher Server

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#370]
Deploy k3s as a local cluster and deploy rancher-server enabled using AutoK3s.

The UI form needs to provide interactive input for key parameters of Rancher-Server Helm Chart.

**Comment by niusmallnan** [comment]
I think we can try to integrate [kubeapps](https://github.com/kubeapps/kubeapps).

Here are my steps:

Install kubeapps
https://github.com/kubeapps/kubeapps/blob/main/docs/user/getting-started.md

Add rancher helm repo by kubeapps
<img width="1677" alt="截屏2022-02-10 上午11 36 37" src="https://user-images.githubusercontent.com/998984/153332507-2feb15cf-c405-4e9d-82e5-4c860c655bec.png">

Install rancher by kubeapps
<img width="1670" alt="截屏2022-02-10 上午11 35 55" src="https://user-images.githubusercontent.com/998984/153332443-f5979ca4-8b4c-40b0-b9da-81a8711071d3.png">

**Comment by niusmallnan** [comment]
Please try this: https://github.com/cnrancher/autok3s/tree/master/assets/rancher-setup
