### ISSUE TITLE
[BUG] failed to create native cluster in windows system 

### ISSUE THREAD

**Issue by MSamor** [cnrancher/autok3s#378]
Describe the bug
[INFO] env: Creating environment file /etc/systemd/system/k3s.service.env
[INFO] systemd: Creating service file /etc/systemd/system/k3s.service
[INFO] systemd: Enabling k3s unit
[INFO] systemd: Starting k3s
time="2021-12-30T16:48:54+08:00" level=info msg="[native] successfully created k3s master-1"
apiVersion: v1
clusters:
- cluster:
certificate-authority-data: 
server: https://127.0.0.1:6443
name: default
contexts:
- context:
cluster: default
user: default
name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
user:
client-certificate-data: 
client-key-data: 
time="2021-12-30T16:48:55+08:00" level=error msg="[native] failed to create cluster: read C:\\Users\\Administrator/.autok3s/.kube/config: The process cannot access the file because another process has locked a portion of the file."
time="2021-12-30T16:48:55+08:00" level=info msg="[native] executing rollback logic..."
time="2021-12-30T16:48:55+08:00" level=info msg="[native] instances [120-79-XX-XX] will be rollback"

Environments
 - AutoK3s Version v0.4.6
 - Windows server 2012 R2

**Comment by Jason-ZW** [comment]
It is possible that another process has opened or is using this file

**Comment by MSamor** [comment]
> It is possible that another process has opened or is using this file

I try to reboot and run a autok3s.exe in cmd , the problem also appear. Is there anything I need to do?

**Comment by Jason-ZW** [comment]
try to change `AUTOK3S_CONFIG` env, this environment variable controls the configuration file root path for autok3s.

**Comment by MSamor** [comment]
> Does the current user have the correct permissions for this directory `C:\Users\Administrator/.autok3s/.kube`?
>
> Try to change another directory through `AUTOK3S_CONFIG` env, this environment variable controls the configuration file root path for autok3s.
>
> ```
> # Linux example
> mkdir -p /home/ubuntu/.autok3s
> export AUTOK3S_CONFIG=/home/ubuntu/.autok3s
> 
> # Then try to run autok3s
> autok3s xxxxxx
> ```

Thank you for your reply. 
I'm using an administrator Account.
I try to change AUTOK3S_CONFIG env , but

`time="2021-12-30T19:08:19+08:00" level=error msg="create cluster error: read C:\\server\\autok3s/.kube/config: The process cannot access the file because another process has locked a portion of the file."`

It doesn't matter. Now , i made it run perfectly on Linux.
