### ISSUE TITLE
[Feature Request] Support K8s provider

### ISSUE THREAD

**Issue by eldad87** [cnrancher/autok3s#382]
Provide an ability to deploy K3s into a running K8s (or a compliant alternative e.g. K3s itself) cluster.
This approach can be used to create a multi-tenancy cluster and leverage managed K8s solutions (EKS, AKS, etc) to its advantage;  node auto-scale, strong security enforcement and much more.

**Describe alternatives you've considered**
Namespace isolation.

**Comment by orangedeng** [comment]
This issue is the same as https://github.com/cnrancher/autok3s/issues/335. Closing this one and follow up in 335.
