### ISSUE TITLE
[BUG] FATA[0000] stat /root/.ssh/id_rsa: no such file or directory just use password to create cluster

### ISSUE THREAD

**Issue by 631068264** [cnrancher/autok3s#391]
**Describe the bug**
```
[root@Server-c49a7057-d19d-4676-bafa-e7729889c6fa ~]# /usr/local/bin/autok3s create --provider native --cluster --name test --k3s-install-script '-k http://xxxx/install.sh' --k3s-version v1.19.5+k3s2 --ssh-user root --ssh-password xxx --ssh-port 22  --master-extra-args '--docker' --master-ips xxxx

FATA[0000] stat /root/.ssh/id_rsa: no such file or directory 
```

**To reproduce**
My machine don't have `/root/.ssh/id_rsa` this file . Because I  just use password to connect the node， I don't why I should have a private key.  

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS:  centos7
 - AutoK3s Version
 Version: {"gitVersion":"v0.4.6","gitCommit":"4537e6ee2aea8b204a72f7b6c377edb154f7c058","gitTreeState":"","buildDate":"2021-12-28T04:15:30Z","goVersion":"go1.16.2","compiler":"gc","platform":"linux/amd64"}

**Additional context**

**Comment by Jason-ZW** [comment]
this [commit](https://github.com/cnrancher/autok3s/commit/88ddb3f4e6ecefcd85e07ddfe77be9c1b429c943) will fix the bug.
