### ISSUE TITLE
[BUG] cross build binary package much bigger than repo  in v4.0.7 and Developers' Guide not work for me

### ISSUE THREAD

**Issue by 631068264** [cnrancher/autok3s#405]
**Describe the bug**
<img width="1322" alt="image" src="https://user-images.githubusercontent.com/8144089/158496700-d24664cf-9c50-4286-83d8-b1aab80f4375.png">

I use `dapper  cb only`  

<img width="626" alt="image" src="https://user-images.githubusercontent.com/8144089/158496743-931dbdb7-b905-4640-a09f-c24d2477d5bf.png">

The cmd in [Developer guide](https://github.com/cnrancher/autok3s#developers-guide) not work for me
```
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Makefile:40: warning: overriding recipe for target 'autok3s'
Makefile:8: warning: ignoring old recipe for target 'autok3s'
[INFO] [0316 01:10:02] # make autok3s make autok3s build
[FATA] [0316 01:10:02] unknown action 'make', select from mod,lint,build,unit,verify,package,deploy,e2e
Makefile:40: recipe for target 'autok3s' failed
make: *** [autok3s] Error 1
FATA[0045] exit status 2                    
```

**To reproduce**
I use macOS and I  run  `dapper  cb only`  

**Expected behavior**

**Screenshots**

**Environments (please complete the following information):**
 - OS: macOS 12.2
 - AutoK3s Version [v0.4.7]

**Additional context**

**Comment by Jason-ZW** [comment]
Try to use the `CROSS=true make autok3s cross_build` command on Linux.

You can build the binary file directly in darwin:
Try to use `make autok3s build only`

**Comment by JacieChao** [comment]
The binary package is smaller in the release list because we use `upx` to compressed the file.

**Comment by 631068264** [comment]
@JacieChao Can you give me an example to how you use `upx`   just `upx file` ?

**Comment by Jason-ZW** [comment]
`brew install upx`
`upx -9 autok3s_drawin_amd64`

**Comment by 631068264** [comment]
> Try to use the `CROSS=true make autok3s cross_build` command on Linux.
> 
> You can build the binary file directly in darwin: Try to use `make autok3s build only`

Use this get error
```
[INFO] [0316 10:18:24] crossed building
[INFO] [0316 10:18:24] building linux/amd64
# runtime/cgo
linux_syscall.c:67:13: error: implicit declaration of function 'setresgid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:67:13: note: did you mean 'setregid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:593:6: note: 'setregid' declared here
linux_syscall.c:73:13: error: implicit declaration of function 'setresuid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
linux_syscall.c:73:13: note: did you mean 'setreuid'?
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/unistd.h:595:6: note: 'setreuid' declared here
[FATA] [0316 10:18:28] /Users/wyx/union_workspce/autok3s/hack/make-rules/autok3s.sh:82 'GOOS=${os} GOARCH=${arch} CGO_ENABLED=1 go build -ldflags "${version_flags} ${flags} ${ext_flags}" -tags netgo -o "${CURR_DIR}/bin/autok3s_${os}_${arch}" "${CURR_DIR}/main.go"' exited with status 2
       call stack:
       1: /Users/wyx/union_workspce/autok3s/hack/make-rules/autok3s.sh:337 cross_build(...)
       2: /Users/wyx/union_workspce/autok3s/hack/make-rules/autok3s.sh:346 entry(...)
[FATA] [0316 10:18:28] exiting with status 1
make: *** [autok3s] Error 1

```

**Comment by Jason-ZW** [comment]
Better run cross-build on Linux.
