### ISSUE TITLE
[BUG] How to use autok3s join new nodes when existed a cluster  not created by autok3s

### ISSUE THREAD

**Issue by 631068264** [cnrancher/autok3s#407]
**Describe the bug**

I have a cluster **created by k3s** not autok3s, when I use autok3s to join a new node I get error 
```
cluster xxxx is not exist
```
I read the code found that autok3s throw this because the **autok3s.db** in **.autok3s dir**

How to init this db ?   It's impossible recreate a new cluster.

 - AutoK3s Version [e.g. v0.4.7]

**Additional context**

**Comment by Jason-ZW** [comment]
Starting from version v0.4.7 `native provider` does not support adding nodes to a cluster that is not managed by AutoK3s.

**Comment by Jason-ZW** [comment]
The node addition function only supports clusters created by Autok3s

**Comment by 631068264** [comment]
> Starting from version v0.4.7 `native provider` does not support adding nodes to a cluster that is not managed by AutoK3s.

I use older version autok3s to create cluster , use 0.4.7 join node  also get same error

**Comment by Jason-ZW** [comment]
try v0.4.6？

**Comment by JacieChao** [comment]
We supported managing cluster lists handled by `native` provider in v0.4.7, but we don't save cluster information in the previous version. So the migration is not supported for now.
We will reconsider this situation in the next version.

**Comment by 631068264** [comment]
One more bug , when I create cluster failed , I can't recreate the cluster with a same name.

**Comment by JacieChao** [comment]
@631068264 Could you please provide how to reproduce the problem? 
I tried to create a cluster by `native` provider. If the cluster status is `Failed`, I can recreate the cluster with the same name no matter from UI (Back to Edit) or from CLI.

**Comment by 631068264** [comment]
Oh, I am very sorry. I made a mistake ,it occurred for a long time and suddenly remembered it yesterday .  Create cluster  success， and then use `k3s_uninstall.sh` to  uninstall the cluster，when I recreate use the same name. I get the error.

I must del .autok3s dir  when uninstall the cluster

**Comment by JacieChao** [comment]
fixed in v0.4.9
