### ISSUE TITLE
[Feature Request] Deleting cluster, missing `deleting/removing` status

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#409]
Deleting cluster, missing `deleting/removing` status

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/19684717/159264561-a14dee2e-d737-44fd-b662-bd59a95abb6f.png">

**Comment by JacieChao** [comment]
@ly5156 
Need to support `Removing` status for clusters in UI.
