### ISSUE TITLE
[Feature Request] Add the option to download the specified cluster kubeconfig on the UI

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#420]
It is recommended to add the option to download the specified cluster kubeconfig on the UI, so that users can save the kubeconfig locally and use kubectl to connect to the cluster.

**Comment by JacieChao** [comment]
@ly5156

**Comment by ly5156** [comment]
ui demo:
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/3406205/165025752-23002397-f9ba-4426-b6b6-089da36bdb49.png">
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/3406205/165025944-d9879b63-a375-40aa-b3dc-18daf4793096.png">
