### ISSUE TITLE
[BUG] Cannot access to UI with Firefox on windows 11 

### ISSUE THREAD

**Issue by jack-liew** [cnrancher/autok3s#426]
OS：windows11
running:autok3s -d serve
the response:
time="2022-04-02T08:20:45+08:00" level=debug msg="failed to collected usage metrics: 422 Unprocessable Entity"
time="2022-04-02T08:20:45+08:00" level=info msg="run as daemon, listening on 127.0.0.1:8080"

When I access https://127.0.0.1:8080 in browser
the response:
Secure Connection Failed
An error occurred during a connection to 127.0.0.1:8080. SSL received a record that exceeded the maximum permissible length.
Error code: SSL_ERROR_RX_RECORD_TOO_LONG

When I access http://127.0.0.1:8080 in browser
the response is blank page.

thanks

**Comment by JacieChao** [comment]
@jack-liew Which kind of browser are you using? Could you please try Chrome or Firefox?

**Comment by jack-liew** [comment]
I use friefox and ms edge .

**Comment by JacieChao** [comment]
Firefox works fine for me. Could you please try to open the F12 to see what kind of error occurs in the Firefox Console?

**Comment by jack-liew** [comment]
http://localhost:8080:
Loading module from “http://localhost:8080/ui/assets/index.cafcc866.js” was blocked because of a disallowed MIME type (“text/plain”).

https://127.0.0.1:8080
Cookie “_dd_s” will be soon treated as cross-site cookie against “https://127.0.0.1:8080/ui/” because the scheme does not match.

**Comment by JacieChao** [comment]
Which version of Firefox are you using?

**Comment by jack-liew** [comment]
my firefox version is :98.0.2 (64-bit)
edge 99.0.1150.55 (64bit)

thanks

**Comment by JacieChao** [comment]
I'm using Firefox 98.0.2(64-bit) but the UI works fine for me. Is this error occurring on your Firefox Console?
```
Loading module from “[http://localhost:8080/ui/assets/index.cafcc866.js”](http://localhost:8080/ui/assets/index.cafcc866.js%E2%80%9D) was blocked because of a disallowed MIME type (“text/plain”).
```

**Comment by jack-liew** [comment]
yes, the browser is same version,and the error as you said.

**Comment by JacieChao** [comment]
Which version of AutoK3s are you using?

**Comment by jack-liew** [comment]
yesterday I user autok3s viersion is 0.4.8, today update to 0.4.9.
Did I have other preparations that  didn't do?
because I just did:
download exe file,and changed it's fielname to autok3s.exe,then running:autok3s.exe -d serve.

**Comment by JacieChao** [comment]
Hmmm..... I also download the exe file and ran with the same command. 
How about clearing all cache for Firefox or using a private window and try again?

**Comment by jack-liew** [comment]
......in private tab, It's still view a blank page.
firefox console message is:
Loading module from “http://127.0.0.1:8080/ui/assets/index.cafcc866.js” was blocked because of a disallowed MIME type (“text/plain”).
Loading failed for the module with source “http://127.0.0.1:8080/ui/assets/index.cafcc866.js”.

**Comment by JacieChao** [comment]
It's curious why the browser changes the javascript type file to text/plain...
@ly5156 Do you have any ideas?

**Comment by jack-liew** [comment]
thank for your help!
I'll try to search the answer.
thank again.

**Comment by ly5156** [comment]
@jack-liew  
You can clear your browser cache and try refreshing your browser
chrome example:
<img width="967" alt="image" src="https://user-images.githubusercontent.com/3406205/161367804-0c19af30-3a5e-4c6d-8634-75144127d1fd.png">

**Comment by jack-liew** [comment]
> @jack-liew You can clear your browser cache and try refreshing your browser chrome example: <img alt="image" width="967" src="https://user-images.githubusercontent.com/3406205/161367804-0c19af30-3a5e-4c6d-8634-75144127d1fd.png">

> 
To clear cache not worked.
when i F12 to Find the problem, it view message:
Loading module from “[http://localhost:8080/ui/assets/index.cafcc866.js”](http://localhost:8080/ui/assets/index.cafcc866.js%E2%80%9D) was blocked because of a disallowed MIME type (“text/plain”).
-----------------
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Headers/X-Content-Type-Options
Blocks a request if the request destination is of type style and the MIME type is not text/css, or of type script and the MIME type is not a [JavaScript MIME type](https://html.spec.whatwg.org/multipage/scripting.html#javascript-mime-type).
------------------
It looks like autok3s web server has a bug about MIME type.

Thanks

**Comment by JacieChao** [comment]
@jack-liew I think it's a problem with Windows registry configuration. Could you please try to modify registry config as the following comments to check if this issue could be fixed?
https://github.com/golang/go/issues/32350#issuecomment-635859542

More information: https://stackoverflow.com/questions/59355194/python-flask-error-failed-to-load-module-script-strict-mime-type-checking-i

**Comment by jack-liew** [comment]
It's worked,Thanks,
but I don't think it be a good idea.

**Comment by JacieChao** [comment]
This won't reproduce on every version of Windows. I didn't reproduce it on my Windows 10 computer. 
https://github.com/golang/go/issues/32350#issuecomment-635859542 is a temporary solution. 

We will deep dive to see how to handle this issue more conveniently.
