### ISSUE TITLE
[BUG] use web ui to creating a cluster, failed to start kube-explorer for cluster test1

### ISSUE THREAD

**Issue by jack-liew** [cnrancher/autok3s#432]
os:debian 10.2
user:root
--------------
when I use autok3s web ui to create a cluster,it tip:

time="2022-04-08T16:37:06+08:00" level=error msg="[native] failed to start kube-explorer for cluster test1: exec: \"kube-explorer\": executable file not found in %PATH%"
tee: /var/lib/rancher/k3s/server/manifests/ui.yaml: No such file or directory
---------------
What should I do?

Thanks

**Comment by JacieChao** [comment]
You can use the following command to install both AutoK3s and kube-explorer on your host
```
curl -sS http://rancher-mirror.cnrancher.com/autok3s/install.sh  | sh
```
Or you can download [kube-explorer](https://github.com/cnrancher/kube-explorer/releases/tag/v0.2.8) manually.

**Comment by Jason-ZW** [comment]
Any question please re-open this issue
