### ISSUE TITLE
[Feature Request]support install and upgrade by native in air-gapped environmemt

### ISSUE THREAD

**Issue by codering** [cnrancher/autok3s#448]
**Describe the solution you'd like**

We can agree on a directory to store the k3s offline installation package and version, and then we can choose to install or upgrade through ui or cli

**Comment by orangedeng** [comment]
The design docs is available here: https://github.com/cnrancher/autok3s/discussions/480. Any comments or discussion are very welcome.

**Comment by sniperking1234** [comment]
Is there a release plan for version v0.6?

**Comment by Jason-ZW** [comment]
@sniperking1234 
You can follow the 0.6.0 milestone progress, which will be released once we complete the issues in the milestone.

**Comment by ly5156** [comment]
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/3406205/197157270-b9f0f2a1-2e10-4b9e-8384-18006e63aac5.png">
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/3406205/197157328-a67f8cb6-ff85-40b8-80dd-ed05c497d44a.png">
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/3406205/197157452-4f1fac70-2064-46e0-83ab-973bd26f51f6.png">
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/3406205/197157480-00bc073b-ee20-4537-864e-ff5be8fb4b83.png">

Edit Air gap package
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/3406205/197157588-f9ff3299-c165-46cc-96ca-195d8a0677c5.png">

**Comment by ly5156** [comment]
1. 创建集群支持 air-gap package install

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/3406205/198549869-2193bb91-70d4-41c8-9d61-88609922f0bc.png">
2. 更新集群支持 air-gap package upgrade
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/3406205/198550133-4bd003ee-bae2-480f-b0b5-b6c920d1ec87.png">
