### ISSUE TITLE
[Enhancement] Update cloud providers' CCM and add-on components

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#463]
These components need to be updated.
- [x] alibaba/ccm v1.9.3.239-g40d97e1-aliyun -> v2.4.0
- [x] tencent/ccm v1.0.1 -> v1.0.1
- [x] google/ccm v4.10.0 -> v4.12.0
- [x] aws/ccm v1.19.0-alpha.1 -> multi-version

**Comment by Jason-ZW** [comment]
Tested:
- alibaba provider
- google provider

**Comment by orangedeng** [comment]
Tested:

- aws provider
- tencent cloud provider
