### ISSUE TITLE
[BUG] aws provider, only supports us-east-1a region?

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#465]
**Describe the bug**
aws provider, failed to create cluster when selecting `ca-central-1` region

**To reproduce**
1. Create a template, select `ca-central-1` region, and fill in the others correctly
2. Create a cluster from a template

Failed to create, prompt: `can't get subnets for vpc vpc-09aecb61 at zone us-east-1a`

**Expected behavior**
Successfully created cluster in `ca-central-1` region

**Screenshots**
<img width="1580" alt="image" src="https://user-images.githubusercontent.com/19684717/178098835-0b1546a7-1f53-47b6-b00d-7e1b1cb608da.png">

**Environments (please complete the following information):**
 - OS: [e.g. Darwin Bigsur] macOS Monterey
 - AutoK3s Version [e.g. v0.4.0] 
Version: {"gitVersion":"v0.5.1","gitCommit":"4ec0a56cc45c2b7e1bfa33f5f4f6820a302203db","gitTreeState":"","buildDate":"2022-06-27T03:54:28Z","goVersion":"go1.17.11","compiler":"gc","platform":"darwin/amd64"}

**Comment by kingsd041** [comment]
Is it because the default zone is us-east-1a？

**Comment by Jason-ZW** [comment]
You need to select Availability Zone
