### ISSUE TITLE
[Feature Request] Remove Kubernetes Dashboard Support

### ISSUE THREAD

**Issue by orangedeng** [cnrancher/autok3s#471]
As we supported kube-explorer as the k3s UI, we don't need Kubernetes Dashboard. We can remove this support.

**Comment by orangedeng** [comment]
Also need to remove dashboard options in autok3s create cluster ui. @ly5156

**Comment by ly5156** [comment]
@orangedeng 
delete the `dashboard` options?
<img width="849" alt="image" src="https://user-images.githubusercontent.com/3406205/180722914-843e14cf-5429-44d2-a260-876ee4ceaf80.png">

**Comment by orangedeng** [comment]
yes
