### ISSUE TITLE
[BUG] Please fix the fail link

### ISSUE THREAD

**Issue by zsnmwy** [cnrancher/autok3s#484]
**Describe the bug**

https://github.com/cnrancher/autok3s/blob/af4e939e4ad7f0a01c1dec2c416b8b40ed1f9497/scripts/install.sh#L26-L29

![image](https://user-images.githubusercontent.com/35299017/182076195-c1cf7362-6a98-4419-a3f6-5cd8998ac339.png)

Ref: https://github.com/cnrancher/docs-rancher2/pull/771

**Comment by orangedeng** [comment]
The install script is now using aliyun OSS site instead. It should work. Closing this issue.

Feel free to reopen this issue if necessary.
