### ISSUE TITLE
[Feature Request]Maybe supporting add-ons like kube-app after cluster setup.

### ISSUE THREAD

**Issue by orangedeng** [cnrancher/autok3s#499]
Use https://github.com/komodorio/helm-dashboard as helm dashboard. Run it like kube-explorer.

**Comment by orangedeng** [comment]
> Why not considering to use https://github.com/vmware-tanzu/kubeapps?

kubeapps requires a k8s cluster to install, we want to make it light weight and can start/stop with autok3s UI.

**Comment by JacieChao** [comment]
- [ ] Add `autok3s helm-dashboard` to enable the helm-dashboard server by CLI.
- [ ] Add Helm-dashboard switch button to enable or disable helm-dashboard. Users can enable helm-dashboard when they have at least 1 K3s cluster created by AutoK3s.
- [ ] Add a dashboard link button to each cluster like kube-explorer.
- [ ] Users can link to the helm-dashboard UI from each cluster.
- [ ] Add install helm-dashboard script to install script and add helm-dashboard tool to Dockerfile.

We need to check the helm-dashboard version before each Release of AutoK3s.

**Comment by ly5156** [comment]
UI demo:
<img width="1212" alt="image" src="https://github.com/cnrancher/autok3s/assets/3406205/8b295e93-220b-48f0-90f4-5a6963cbb975">

**Comment by orangedeng** [comment]
Test passed with v0.9.0-rc3
