### ISSUE TITLE
[Feature Request] Better Support for AWS AMI selection

### ISSUE THREAD

**Issue by orangedeng** [cnrancher/autok3s#500]
Maybe we can support AMI selection like the UI in AWS.

![截屏2022-08-29 15 50 07](https://user-images.githubusercontent.com/15376837/187151462-c824c7f1-a4d6-4709-b5f9-8f0b88fa9845.png)

Better to have AMI grouped by OS provider, volume type and arch. Also shows the verified OS image first.

**Comment by ly5156** [comment]
The current AWS image interface returns limited information about the image data, how to display, think again, the following is the data structure returned by the image list interface

<img width="661" alt="image" src="https://user-images.githubusercontent.com/3406205/188577129-e75735cf-eab9-48d3-afb9-45fe41944316.png">

**Comment by ly5156** [comment]
1. Support for secondary filtering of results
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/3406205/188816709-42e17ec6-3439-4c45-9bd2-3d41b3954b05.png">

**Comment by Jason-ZW** [comment]
We need to redesign this page, we will discuss with you in detail later

**Comment by ly5156** [comment]
aws quick start page：parameters used to load the image via js sdk
```js

      ubuntu: {
        ownerIds: ['099720109477', '898082745236', '652529143229'],
        namePrefix: 'ubuntu/images/hvm-ssd/ubuntu-'
      },
      amazonLinux: {
        ownerIds: ['137112412989', '690405935483', '898082745236'],
        namePrefix: 'amzn2-ami-kernel-'
      },
      redHat: {
        ownerIds: ['309956199498', '199830906635'],
        namePrefix: 'RHEL-'
      },
      suseLinux: {
        ownerIds: ['013907871322'],
        namePrefix: 'suse-sles-'
      },
      debian: {
        ownerIds: ['136693071363'],
        namePrefix: 'debian-'
      }
    }
```

**Comment by ly5156** [comment]
ui demo:
![aws-image-select](https://user-images.githubusercontent.com/3406205/204174784-bd0c5e08-deea-4c08-a054-a6f8abd56aae.gif)

**Comment by TangStone** [comment]
Validate in v0.7.0-rc1

**Validation target**
  - Filtering the selected ami in the autok3s AWS AMI selection UI can be found in the aws ami directory

**Verification steps**
1. Select ap-northeast-1 for region, install the following conditional filtering, and finally select ami-0e2bf1ada70fd3f33
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/15829074/210513715-bb4dfbb0-63ea-45f3-8605-8e11c53a28be.png">
2. Select ap-northeast-1 in the aws ami directory area region of aws, and enter ami-0e2bf1ada70fd3f33 in the input search box to finally display the ami
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/15829074/210514258-357863aa-1a01-4f54-8bac-9a545ab765de.png">
3. In the same process, Amazon Linux, Red Hat, Suse Linux and Debian are verified and passed
