### ISSUE TITLE
[BUG] Cluster join node error

### ISSUE THREAD

**Issue by sniperking1234** [cnrancher/autok3s#501]
**Describe the bug**

**To reproduce**
1. Go to Cluster Page
2. Click on Join Node
3. Input Master IP or Worker IP
4. Click Save button
5. See an error

**Screenshots**
![image](https://user-images.githubusercontent.com/7834655/191229719-05901089-06b7-46d2-b550-6d7c99fa77a3.png)
![image](https://user-images.githubusercontent.com/7834655/191229799-08355725-8833-413e-8508-7e984518702c.png)

**Environments (please complete the following information):**
 - OS: Anolis OS release 8.6
 - AutoK3s Version  v0.5.2

**Comment by Jason-ZW** [comment]
@ly5156 Could you please take a look at this issue？
