### ISSUE TITLE
[Feature Request] Disable automatic execution of uninstall k3s function

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#504]
If autok3s fails to create a k3s cluster, the unloading logic will be executed automatically. In this way, the error log of k3s cannot be viewed, and the cause of the problem cannot be checked, as shown in the following figure:

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/19684717/191908240-13e85b79-3a97-4a92-b62c-1139bbaf6779.png">

We should limit the automatic execution of the uninstallation logic by parameters, so that we can connect to the host and view the error log of K3s.

We should also remind users that the cluster created by this mode is only suitable for troubleshooting, and if it fails, the k3s cluster needs to be uninstalled manually.

**Comment by orangedeng** [comment]
Tested with creating cluster via wrong master args. While setting `--rollback=false`, the cluster won't rollback after creation failed. And deleting cluster will run the rollback logic.

**Comment by orangedeng** [comment]
Maybe we need to expose this feature to web UI also. And we need to update docs for this too.

**Comment by JacieChao** [comment]
Yes. We already add a debug button on UI in create cluster form. Will update docs for this feature after UI commit merged.

**Comment by ly5156** [comment]
UI demo
<img width="1217" alt="image" src="https://github.com/cnrancher/autok3s/assets/3406205/3a4c9fb7-5657-4f90-baa7-74376e478eb0">

**Comment by orangedeng** [comment]
Already tested with CLI and webUI, no rollback function works as expected
