### ISSUE TITLE
[BUG] Install script on Readme install directions leads to a test page 

### ISSUE THREAD

**Issue by Opswatch** [cnrancher/autok3s#505]
**Describe the bug**
When trying to install using curl -sS https://rancher-mirror.rancher.cn/autok3s/install.sh  | sh it leads to a test page, on the command prompt we get a Syntax error: redirection unexpected

**To reproduce**
1. Run curl -sS https://rancher-mirror.rancher.cn/autok3s/install.sh  | sh
2. See an error

**Expected behavior**
Expecting script to download and run.

**Environments (please complete the following information):**
 - OS: Ubuntu

**Comment by niusmallnan** [comment]
It may be blocked by some firewall.

Please try this mirror site: https://rancher-mirror.oss-cn-beijing.aliyuncs.com/autok3s/install.sh

**Comment by tomiaa1926** [comment]
> It may be blocked by some firewall.
> 
> Please try this mirror site: https://rancher-mirror.oss-cn-beijing.aliyuncs.com/autok3s/install.sh

You also seem to have a problem with this url `https://rancher-mirror.oss-cn-beijing.aliyuncs.com/autok3s/install.sh`

Failed while attempting to install autok3s. Please manually install:
1. Open your web browser and go to https://github.com/cnrancher/autok3s/releases
2. Download the latest release for your platform. Call it 'autok3s'.
3. chmod +x ./autok3s
4. mv ./autok3s /usr/local/bin

**Comment by Jason-ZW** [comment]
Thanks for the feedback issue.
The corresponding `install.sh` URL in `README.md` has been changed, please reopen this issue if there is any problem.
