### ISSUE TITLE
[BUG] Quick start create

### ISSUE THREAD

**Issue by tomiaa1926** [cnrancher/autok3s#507]
K3s Install Script The opening is blank

You also seem to have a problem with this address `https://rancher-mirror.rancher.cn/k3s/k3s-install.sh`

**Comment by niusmallnan** [comment]
Try this: https://github.com/cnrancher/autok3s/issues/505#issuecomment-1264187035

**Comment by Jason-ZW** [comment]
Thanks for the feedback issue.
The corresponding `install.sh` URL in `README.md` has been changed, please reopen this issue if there is any problem.

**Comment by tomiaa1926** [comment]
> Try this: [#505 (comment)](https://github.com/cnrancher/autok3s/issues/505#issuecomment-1264187035)
Thank you for your answer to capture your address autoK3 s not k3s

**Comment by tomiaa1926** [comment]
> install
Sorry，I want to talk about the installation k3s address here.
It looks like you can only choose and  opening is blank

![image](https://user-images.githubusercontent.com/42992957/196096656-805239d4-8656-499b-85a3-4da2a6786d96.png)

**Comment by niusmallnan** [comment]
@tomiaa1926 
You can try this link: https://rancher-mirror.oss-cn-beijing.aliyuncs.com/k3s/k3s-install.sh

In addition to selecting from an existing list, this form can also be filled in manually.

**Comment by tomiaa1926** [comment]
> 
I tried to use this link, but got another error:
Process exited with status 7: curl: (35) gnutls_handshake() failed: Error in the pull function.\n
![image](https://user-images.githubusercontent.com/42992957/197954843-d426a093-70fd-4edd-8275-074e3644faeb.png)

**Comment by Jason-ZW** [comment]
@ly5156 Could you help to test this URL with the `v0.5.2` version?

**Comment by tomiaa1926** [comment]
> @ly5156 Could you help to test this URL with the `v0.5.2` version?

My version is `v0.5.1`

**Comment by ly5156** [comment]
I tested both v0.5.2 and v0.5.1 versions without problems
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/3406205/197958262-2a5d72e7-9f37-4a96-b000-4f500c5f01a3.png">
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/3406205/197959487-63dbc8fe-b285-4ab5-8d17-c32002ca3a7f.png">

**Comment by tomiaa1926** [comment]
> @tomiaa1926 env:
> 
> 1. aws ec2 spot instance
> 2. os: ubuntu lts 20.04
> 
> I tested both v0.5.2 and v0.5.1 versions without problems @Jason-ZW The log shows that 0.5.1 version some files were downloaded from github
> 
> <img alt="image" width="1115" src="https://user-images.githubusercontent.com/3406205/197958262-2a5d72e7-9f37-4a96-b000-4f500c5f01a3.png">
> 
> <img alt="image" width="1276" src="https://user-images.githubusercontent.com/3406205/197959487-63dbc8fe-b285-4ab5-8d17-c32002ca3a7f.png">

Thanks for your test ，Although I don't know why, I switch to version `V0.5.2`, that‘s ok
![image](https://user-images.githubusercontent.com/42992957/197962907-88cf3415-e313-45ff-bf22-5a040163c2cc.png)

**Comment by ly5156** [comment]
@tomiaa1926 
It is possible that your environment does not have access to github, because some files in version 0.5.1 were downloaded from github

**Comment by tomiaa1926** [comment]
> @tomiaa1926 It is possible that your environment does not have access to github, because some files in version 0.5.1 were downloaded from github

Okay, I get it.

**Comment by tomiaa1926** [comment]
> @tomiaa1926 env:
> 
> 1. aws ec2 spot instance
> 2. os: ubuntu lts 20.04
> 
> I tested both v0.5.2 and v0.5.1 versions without problems @Jason-ZW The log shows that 0.5.1 version some files were downloaded from github
> 
> <img alt="image" width="1115" src="https://user-images.githubusercontent.com/3406205/197958262-2a5d72e7-9f37-4a96-b000-4f500c5f01a3.png">
> 
> <img alt="image" width="1276" src="https://user-images.githubusercontent.com/3406205/197959487-63dbc8fe-b285-4ab5-8d17-c32002ca3a7f.png">

Now it seems that stand-alone mode is normal, and you have tested too many machine cluster modes.
