### ISSUE TITLE
[Feature Request] K3d Provider needs to be bumped

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#512]
The current K3d provider version is `v5.2.2`
Needs to be bumped to `v5.4.4` or later

**Comment by Jason-ZW** [comment]
Need to update with harvester provider

**Comment by orangedeng** [comment]
Depends on PR https://github.com/harvester/harvester/pull/2696 for harvester provider update.

**Comment by orangedeng** [comment]
Refer to https://github.com/cnrancher/autok3s/pull/543#issuecomment-1365689829, we don't have any solution for it. Move out of v0.7.0 milestone.

**Comment by TangStone** [comment]
autok3 从v0.6.0升级到v0.7.0-rc2版本，原k3d一直处于stop状态

详细步骤
1. 在ubuntu-18.04(8c8g)实例，  docker 启动 autok3s 0.6.0 版本 ，并通过quickstart创建k3d集群，aliyun集群
```
docker run -itd --restart=unless-stopped --net host -v /var/run/docker.sock:/var/run/docker.sock cnrancher/autok3s:v0.6.0

```
2. 通过以下方式升级0.6.0到0.7.0-rc2版本，
```
docker stop <old-container>
docker run -itd --restart=unless-stopped -p 8080:8080 --volumes-from <old-container> cnrancher/autok3s:v0.7.2-rc2
```

3. 查看autok3s ui ,原aliyun集群正常运行，k3d集群一直处于stop状态，使用升级的版本，可以成功创建新的k3d集群

**Comment by orangedeng** [comment]
感觉不是一个升级的问题，当我在v0.6.1重启 autok3s的容器时，同样会出现k3d集群stop的情况

**Comment by TangStone** [comment]
Binary file deployment - upgrading autok3 from v0.6.0 to v0.7.0-rc2 has no impact on the operation of the original k3d cluster and the creation of the k3d cluster

**Detailed steps**

1. On the ubuntu-18.04 (248g) instance, after entering the instance, pull https://github.com/cnrancher/autok3s/releases/download/v0.6.0/autok3s_linux_amd64 File and grant execution permission, and move it to the/usr/local/bin directory
2. Start autok3s v0.6.0
3. Access the autok3s ui through the instance address, and create a k3d cluster. The aliyun cluster runs successfully
4. Stop running autok3s v0.6.0
5. Pull in the instance https://github.com/cnrancher/autok3s/releases/download/v0.7.0-rc2/autok3s_linux_amd64 File, assign execution permission and move to/usr/local/bin directory
6. Start the autok3s v0.7.0-rc2 file
7. Access the autok3s ui again, and the original aliyun cluster and k3d cluster run normally, while the newly created aliyun cluster runs normally
