### ISSUE TITLE
[Enhancement] Improve Cluster Form & Cluster List

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#518]
### UI Experience Enhancement:

Some users have doubts about the use of HA clusters. Although we support configuring HA, the location and linkage of the form do not seem to be very friendly, so users have to delete the cluster and use the correct method to create it after knowing how to create an HA cluster.

- [ ] Add Cloud-Providers' Logo in Cluster List Page & Cluster Templates & Create Page & Quick-Start Page etc...
- [ ] The Cluster List Page needs to show whether it is an HA Cluster.
- [ ] The Cluster List Page needs to show the Cluster‘s DataStore type.
- [ ] When the number of masters `>= 2` is selected and the Embedded `ETCD` DataStore is selected, the UI form needs automatically selects the `--cluster` mode, Others DataStore types with HA mode UI needs to give a prompt message.
- [ ] The position of the cluster parameter form needs to be adjusted to the same level as quick-start.
- [ ] The dropdown form entries need to be sorted, such as `Instance Type` etc. (`Instance Type` change to `Machine Type`)
- [ ] Add a required asterisk (*).
- [ ] Add placeholder message.
- [ ] All `Advance show` link text needs to be changed to `Show Advanced`.
- [ ] `Instance Options` needs to be changed to `Machine Options`.
- [ ] `K3s Options` needs to be changed to `K3s Cluster Options`.
- [ ] `Additional Options` needs to be chaged to `Add-on Options`.
- [ ] All others Cloud-Providers Credential form needs to use the `Dropdown` component as Google Provider.

**Comment by ly5156** [comment]
1. HA Mode Form Improvements
![k3s_options_datastore](https://user-images.githubusercontent.com/3406205/202377969-2d2cd634-c24b-4027-9cda-68144717a2df.gif)

**Comment by ly5156** [comment]
@Jason-ZW 
autok3s server may need to open the following parameters for users to set
`--datastore-cafile`,`--datastore-certfile`,`--datastore-keyfile`
ref:
`https://docs.k3s.io/installation/datastore#external-datastore-configuration-parameters`

**Comment by ly5156** [comment]
2. quick-start can edit all config
![quick-start](https://user-images.githubusercontent.com/3406205/202995667-848291da-1c99-45c2-89ff-5e750d59ca89.gif)

**Comment by ly5156** [comment]
3. google,aws, alibaba, tencent providers  support credential select:

<img width="1386" alt="image" src="https://user-images.githubusercontent.com/3406205/203485932-d97f4754-a4a7-42ce-968d-294c5cae248d.png">

**Comment by ly5156** [comment]
1. instance type have been sorted
2. instance type support filter
3. show instance type label
![aws-instance-type](https://user-images.githubusercontent.com/3406205/204235221-d34f52c5-3226-4508-b71e-de0ebb06272e.gif)

**Comment by ly5156** [comment]
1. show privider logo

![provider-logo](https://user-images.githubusercontent.com/3406205/205243322-8a79931e-82e4-4d97-875f-ae0daad50eea.gif)

**Comment by ly5156** [comment]
support display HA mode and datastore type

<img width="1288" alt="image" src="https://user-images.githubusercontent.com/3406205/207542730-05b5bf64-08b1-48fd-8638-e354faf2dfd5.png">

**Comment by ly5156** [comment]
support datastore CA file, Cert File and Key file config

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/3406205/207543386-ec207e38-853e-4a72-b6b8-315a0f16e512.png">

**Comment by ly5156** [comment]
- [x] Add Cloud-Providers' Logo in Cluster List Page & Cluster Templates & Create Page & Quick-Start Page etc...
- [x]  The Cluster List Page needs to show whether it is an HA Cluster.
- [x]  The Cluster List Page needs to show the Cluster‘s DataStore type.
- [x]  When the number of masters >= 2 is selected and the Embedded ETCD DataStore is selected, the UI form needs automatically selects the --cluster mode, Others DataStore types with HA mode UI needs to give a prompt message.
- [x]  The position of the cluster parameter form needs to be adjusted to the same level as quick-start.
- [x]  The dropdown form entries need to be sorted, such as Instance Type etc. (Instance Type change to Machine Type)
- [ ]  Add a required asterisk (*).
- [ ]  Add placeholder message.
- [x]  All Advance show link text needs to be changed to Show Advanced.
- [x]  Instance Options needs to be changed to Machine Options.
- [x]  K3s Options needs to be changed to K3s Cluster Options.
- [x]  Additional Options needs to be chaged to Add-on Options.
- [x]  All others Cloud-Providers Credential form needs to use the Dropdown component as Google Provider.

**Comment by JacieChao** [comment]
1. Add `--datastore-cafile`, `--datastore-certfile`, `--datastore-keyfile` to support datastore server with TLS certificate.
  To validate this situation, we need to prepare a datastore server with TLS certificate, e.g. Mysql with TLS.
  Then using command like:
    ```
    autok3s create -p xxx -n xxx .... --datastore "mysql://username:password@tcp(hostname:3306)/database-name" --datastore-cafile ~/keys/ca.pem --datastore-certfile ~/keys/cert.pem --datastore-keyfile ~/keys/key.pem
    ```
2. Add `HA Mode` and `DataStore type` for cluster list and detailed information.
  ```
  # Add IsHAMode and DatastoreType for list information
  autok3s list

       NAME          REGION      PROVIDER  STATUS   MASTERS  WORKERS     VERSION     ISHAMODE    DATASTORETYPE
    jacie-ha     ap-southeast-2  aws       Running  2        0        v1.23.13+k3s1  true      External DB(mysql)
    jacie-em-ha  ap-southeast-2  aws       Running  1        0        v1.23.13+k3s1  true      Embedded DB(etcd)
    jacie-test   ap-southeast-2  aws       Running  1        0        v1.19.16+k3s1  false
  ```

  ```
  autok3s describe -n jacie-ha

  Name: jacie-ha
  Provider: aws
  Region: ap-southeast-2
  Zone: ap-southeast-2c
  Master: 2
  Worker: 0
  IsHAMode: true
  DataStoreType: External DB(mysql)
  Status: Running
  Version: v1.23.13+k3s1
  Nodes:
    - internal-ip: [x.x.x.x]
      external-ip: [x.x.x.x]
      instance-status: running
      instance-id: xxxxxx
      roles: control-plane,master
      status: Ready
      hostname: xxxxx
      container-runtime: containerd://1.5.13-k3s1
      version: v1.23.13+k3s1
    - internal-ip: [x.x.x.x]
      external-ip: [x.x.x.x]
      instance-status: running
      instance-id: xxxxx
      roles: control-plane,master
      status: Ready
      hostname: xxxxx
      container-runtime: containerd://1.5.13-k3s1
      version: v1.23.13+k3s1
  ```

The features above can also handle by UI.

**Comment by TangStone** [comment]
- [ ] Add Cloud-Providers' Logo in Cluster List Page & Cluster Templates & Create Page & Quick-Start Page etc...
- [ ] The Cluster List Page needs to show whether it is an HA Cluster.
- [ ]  The Cluster List Page needs to show the Cluster‘s DataStore type.
- [ ] When the number of masters >= 2 is selected and the Embedded ETCD DataStore is selected, the UI form needs automatically selects the --cluster mode, Others DataStore types with HA mode UI needs to give a prompt message.
- [ ]  The position of the cluster parameter form needs to be adjusted to the same level as quick-start.
- [ ]  The dropdown form entries need to be sorted, such as Instance Type etc. (Instance Type change to Machine Type)
- [ ] Add a required asterisk (*).
- [ ] Add placeholder message.
- [ ]  All Advance show link text needs to be changed to Show Advanced.
- [ ] Instance Options needs to be changed to Machine Options.
- [ ] K3s Options needs to be changed to K3s Cluster Options.
- [ ] Additional Options needs to be chaged to Add-on Options.
- [ ] All others Cloud-Providers Credential form needs to use the Dropdown component as Google Provider.
