### ISSUE TITLE
[Enhancement] Need use k3s favicon.ico

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#519]
AutoK3s UI needs to use k3s favicon.ico, current is rancher favicon.ico

**Comment by ly5156** [comment]
<img width="668" alt="image" src="https://user-images.githubusercontent.com/3406205/201590583-4f56178f-944e-4899-896f-ee3aafc6506b.png">

**Comment by TangStone** [comment]
Verify on v0.7.0-rc1

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/15829074/210501548-ad59d5c7-e524-4905-a3cb-fb4cdea77bbb.png">


All verification passed
