### ISSUE TITLE
[BUG] Not working on Windows

### ISSUE THREAD

**Issue by doublefx** [cnrancher/autok3s#520]
**Describe the bug**
Any autok3s command is met with:
`level=fatal msg="open C:\\Users\\<USER>\\.autok3s\\.db\\autok3s.db: The system cannot find the path specified."`

**To reproduce**
1. In your path, download [the latest autok3s for windows 64](https://github.com/cnrancher/autok3s/releases/download/v0.6.0/autok3s_windows_amd64.exe) and rename it: `autok3s`
2. run `autok3s version` or `autok3s -d serve` or `autok3s -d create -p k3d --name myCluster --master 1 --worker 1` and get:
level=fatal msg="open C:\\Users\\doublefx\\.autok3s\\.db\\autok3s.db: The system cannot find the path specified.

**Environments (please complete the following information):**
 - OS: Windows 11
 - AutoK3s Version: [v0.6.0](https://github.com/cnrancher/autok3s/releases/tag/v0.6.0)

**Comment by ly5156** [comment]
@doublefx Thanks for your feedback~ Maybe the issue caused by this [commit](https://github.com/cnrancher/autok3s/commit/2e24f006a91c317ea4b06bff2ba3a2126d0d0400).
Workaround:
Create a directory manually then try `autok3s` command again.
```
mkdir C:\Users\doublefx\.autok3s\.db
```

**Comment by Jason-ZW** [comment]
@orangedeng  PTLA this issue.

**Comment by ly5156** [comment]
OS: Windows 11
AutoK3s Version: [v0.6.1-rc1](https://github.com/cnrancher/autok3s/releases/tag/v0.6.1-rc1)

![image](https://user-images.githubusercontent.com/3406205/202081612-4fee0b30-de4c-4387-8ae7-612137521211.png)
