### ISSUE TITLE
[Feature Request] Change to SUSE brands

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#521]
AutoK3s UI needs to be changed to the SUSE brand.

**Comment by ly5156** [comment]
1. button
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/3406205/201586263-858bd66e-0cc6-426a-bbeb-f8856877c374.png">

2. tab label
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/3406205/201586355-7b14fd97-3c63-454e-a65d-43db6ed27cea.png">
 
3. dropdown hover bg
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/3406205/201586753-36b09422-35cb-4dcc-9018-91aee20531df.png">

**Comment by TangStone** [comment]
Verify on v0.7.0-rc1
-  button
- tab label
- dropdown hover bg
- form: border and label change color if input focus
- nav font size and spacing adjustment

All verification passed
