### ISSUE TITLE
[Feature Request]  The drop-down box should support the query function

### ISSUE THREAD

**Issue by kingsd041** [cnrancher/autok3s#531]
version: 0.6.0

The drop-down box should support the query function. After entering the content in the text box, the drop-down box can be filtered

<img width="697" alt="image" src="https://user-images.githubusercontent.com/19684717/201889611-4bbdd802-60c4-4e74-9120-5322b21d2f61.png">

**Comment by ly5156** [comment]
![combo-box-filter](https://user-images.githubusercontent.com/3406205/204756754-b30809af-f65e-4057-afe8-2547c70fce49.gif)

**Comment by TangStone** [comment]
Verified in v0.7.0-rc1
The following options of Machine Options have been verified
- Machine Type
- vpc
- V-Switch
- Security Group
- Key Pair
All verification passed

<img width="1524" alt="image" src="https://user-images.githubusercontent.com/15829074/210497794-ac5e5c5d-9873-41dd-a120-c4286447ce01.png">
