### ISSUE TITLE
[BUG] single node instance fails to start on google

### ISSUE THREAD

**Issue by lalyos** [cnrancher/autok3s#538]
**Describe the bug**
Starting a single-node cluster on google fails.

**Environments (please complete the following information):**
 - OS: Darwin Monterey 12.5.1 (intel)
 - AutoK3s Version: v0.6.1

**Additional context**

I could see the normal process:
- instance is started
- ssh uploaded
- install starts `curl get.k3s.io | ...`
- but it fails: (see log down below)

- I tried it repeatedly, always with the same result.
- normally autok3s will delete the instance, so there is no way to debug
- therefore, when I saw failing message, exited from autok3s and ssh-d directly to the instance

```
$ journalctl -xe
...
-- Unit k3s.service has begun starting up.
Nov 27 07:50:54 autok3s-auto-master-8pjb5 sh[7181]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Nov 27 07:50:54 autok3s-auto-master-8pjb5 sh[7181]: /bin/sh: 1: /usr/bin/systemctl: not found
Nov 27 07:50:54 autok3s-auto-master-8pjb5 k3s[7195]: time="2022-11-27T07:50:54Z" level=fatal msg="no-deploy flag is dep
Nov 27 07:50:54 autok3s-auto-master-8pjb5 systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Nov 27 07:50:54 autok3s-auto-master-8pjb5 systemd[1]: k3s.service: Failed with result 'exit-code'.
Nov 27 07:50:54 autok3s-auto-master-8pjb5 systemd[1]: Failed to start Lightweight Kubernetes.
```

## Failure cause:
The unit file: '/etc/systemd/system/k3s.service' contains a bad reference at `ExecStartPre`
- reference: `/usr/bin/systemctl`
- only exists: `/bin/systemctl`

Seems its related to: https://github.com/k3s-io/k3s/issues/5925
Ubuntu 18.04 is missing that link, while 22.04 has systemctl available on both path

## Proposed Solution:

Maybe the default image for google should be 22.04 instead of 18.04?

## Autok3s log
```
time="2022-11-27T07:51:51+01:00" level=info msg="[cluster] k3s master command: curl -sLS https://get.k3s.io | INSTALL_K
3S_CHANNEL='stable' INSTALL_K3S_EXEC='server --advertise-address=10.156.0.40 --cluster-cidr=10.42.0.0/16 --node-externa
l-ip=34.141.39.45 --tls-san=10.156.0.40 --tls-san=34.141.39.45 --tls-san=auto.k8z.eu --no-deploy traefik' K3S_TOKEN='cf
3001c5fb4a8bcebdad8328028bd9a0' sh -"                                                                                  
[INFO]  Finding release for channel stable                                                                             
[INFO]  Using v1.25.4+k3s1 as release                                                                                  
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.25.4+k3s1/sha256sum-amd64.txt              
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.25.4+k3s1/k3s                            
[INFO]  Verifying binary download                                                                                      
[INFO]  Installing k3s to /usr/local/bin/k3s                                                                           
[INFO]  Skipping installation of SELinux RPM                                                                           
[INFO]  Creating /usr/local/bin/kubectl symlink to k3s                                                                 
[INFO]  Creating /usr/local/bin/crictl symlink to k3s                                                                  
[INFO]  Creating /usr/local/bin/ctr symlink to k3s                                                                     [INFO]  Creating killall script /usr/local/bin/k3s-killall.sh                                                          [INFO]  Creating uninstall script /usr/local/bin/k3s-uninstall.sh                                                      [INFO]  env: Creating environment file /etc/systemd/system/k3s.service.env                                             
[INFO]  systemd: Creating service file /etc/systemd/system/k3s.service                                                 
[INFO]  systemd: Enabling k3s unit                                                                                     
Created symlink /etc/systemd/system/multi-user.target.wants/k3s.service → /etc/systemd/system/k3s.service.             
[INFO]  systemd: Starting k3s                                                                                          
Job for k3s.service failed because the control process exited with error code.
See "systemctl status k3s.service" and "journalctl -xe" for details.
```

**Comment by JacieChao** [comment]
@lalyos Thanks for your feedback!
For my validating environment, the 18.04 can fit K3s v1.22.x or v1.23.x properly. I will check the latest K3s version for this issue and fix it ASAP.

**Comment by lalyos** [comment]
@JacieChao If you want to reproduce the issue add the `--no-deploy traefik`  option:

<img width="876" alt="image" src="https://user-images.githubusercontent.com/464122/204968487-ab00ffec-b857-4484-8817-d6d79e319282.png">

**Comment by JacieChao** [comment]
> @JacieChao If you want to reproduce the issue add the `--no-deploy traefik` option:
> 
> <img alt="Screenshot 2022-12-01 at 5 52 08" width="957" src="https://user-images.githubusercontent.com/464122/204968584-72c6de0e-e7e2-4f16-9566-113fa7176443.png">

Thanks so much, I will check the issue later.

**Comment by BibbyChung** [comment]
I got the same issue. If you want to fix this problem, please change the option from '--no-deploy traefik' to '--disable traefik'.

**Comment by ly5156** [comment]
![master-extra-args](https://user-images.githubusercontent.com/3406205/205822360-69a21a73-f909-4ae6-bb83-59223530cef3.gif)

**Comment by lalyos** [comment]
@JacieChao Thanks for the quick fix in PR280. You are right, that this specific issue, was a combination of multiple things:
- disabling traefik (with the outdated option)
- using an old ubuntu image
- using the latest k3s version: v1.25

But the actually the default image, which is ubuntu 18.04 has issue with non existing systemctl path.
This is a
```
$ k3s --version
k3s version v1.25.4+k3s1 (0dc63334)

$ grep VERSION= /etc/*release
/etc/os-release:VERSION="18.04.5 LTS (Bionic Beaver)"

$ grep systemctl /etc/systemd/system/k3s.service
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'

$ ls -l /usr/bin/systemctl
ls: cannot access '/usr/bin/systemctl': No such file or directory
```

But if I specify to use the image **Ubuntu 22.04** than the systemctl path is fine:
```
$ k3s --version
k3s version v1.25.4+k3s1 (0dc63334)

$ grep VERSION= /etc/*release
/etc/os-release:VERSION="22.04.1 LTS (Jammy Jellyfish)"

$ grep systemctl /etc/systemd/system/k3s.service
ExecStartPre=/bin/sh -xc '! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service'

$ ls -l /usr/bin/systemctl
-rwxr-xr-x 1 root root 1115760 Sep  9 18:47 /usr/bin/systemctl
```

The `ExecStartPre` is checking that : **nm-cloud-setup.service** is not enabled, by
negating the output of `systemctl is-enabled --quiet nm-cloud-setup.service`, but is not
false because its not enabled, but it returns *Exit code: 127 - No such file or directory*

So maybe this **nm-cloud-setup.service** check is not needed, but the **/etc/systemd/system/k3s.service** unit file contains a bad reference when using 18.04 for sure.

Therefor I suggest to change the default Ubuntu image version from 18.04 to 22.04

**Comment by JacieChao** [comment]
@lalyos Thanks for the detailed information. 

Yes, that's another problem. I checked with other Cloud Providers such as AWS has the same issue with the default 18.04 image. We will also upgrade the default Ubuntu image to 22.04 for all Cloud Providers in the next version.
