### ISSUE TITLE
Support Tencent Provider

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#54]

**Comment by NewGr8Player** [comment]
## APIs
- cvm:RunInstances
- cvm:DescribeInstances
- cvm:TerminateInstances
- cvm:StartInstances
- cvm:StopInstances
- cvm:DescribeInstancesStatus
- vpc:AllocateAddresses
- vpc:ReleaseAddresses
- vpc:AssociateAddress
- vpc:DisassociateAddress
- vpc:DescribeAddresses
- vpc:DescribeTaskResult
- tag:DescribeResourcesByTags

## RAMs

> NOTE: Since the cloud platform does not support the resource-level permission assignment of the EIP interface, please ensure that the sub-account can use the following interfaces:
> - vpc:AllocateAddresses
> - vpc:ReleaseAddresses
> - vpc:AssociateAddress
> - vpc:DisassociateAddress
> - vpc:DescribeTaskResult
> - vpc:DescribeAddresses

```
{
    "version": "2.0",
    "statement": [
        {
            "action": [
                "cvm:RunInstances",
                "cvm:DescribeInstances",
                "cvm:TerminateInstances",
                "cvm:StartInstances",
                "cvm:StopInstances",
                "cvm:DescribeInstancesStatus",
            ],
            "resource": "*",
            "effect": "allow"
        },
        {
            "action": [
                "tag:DescribeResourcesByTags"
            ],
            "resource": "*",
            "effect": "allow"
        }
        /* PLEASE ADD YOUR OWN VPC PERMISSION */
    ]
}
```
