### ISSUE TITLE
how to manual installation k3s in autok3s

### ISSUE THREAD

**Issue by jack-liew** [cnrancher/autok3s#553]
My network is hard to download k3s in autok3s, The download speed is only 10k/second.
but i can download autok3s and k3s from other websit fastly, how to manual installation k3s in autok3s?

hope it just like: copy autok3s to /opt/autok3s, copy k3s to /opt/autok3s/k3s.

Thanks

PS: how to manual install k3s in rancher desktop? I got same internet speed problem.

**Comment by JacieChao** [comment]
@jack-liew We have K3s mirror for Chinese users. How about install K3s by `https://rancher-mirror.rancher.cn/k3s/k3s-install.sh`?
If there's also network problem, please try [airgap installation](https://github.com/cnrancher/autok3s/tree/master/docs/i18n/en_us/airgap)

**Comment by jack-liew** [comment]
> @jack-liew We have K3s mirror for Chinese users. How about install K3s by `https://rancher-mirror.rancher.cn/k3s/k3s-install.sh`? If there's also network problem, please try [airgap installation](https://github.com/cnrancher/autok3s/tree/master/docs/i18n/en_us/airgap)


sorry, my bad, autok3s->[K3s Install Script] has aliyun mirror. 

Thank U very much.

**Comment by JacieChao** [comment]
Closing this issue as complete. Please reopen this issue if there's still any problem.
