### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by 779699413** [cnrancher/autok3s#554]
autok3s native installed k3s reported ssh-key error while reading SSH key file: open /root/.ssh/id_rsa: no such file or directory.
Also report an error with the password.
`time="2023-01-09T06:14:22Z" level=info msg="[native] begin to create cluster autok3s..."
time="2023-01-09T06:14:22Z" level=info msg="[native] executing init k3s cluster logic..."
time="2023-01-09T06:14:22Z" level=info msg="[native] creating k3s master-1..."
time="2023-01-09T06:14:22Z" level=info msg="[cluster] k3s master command: curl -sLS https://get.k3s.io | INSTALL_K3S_CHANNEL='stable' INSTALL_K3S_EXEC='server --advertise-address=10.211.55.11 --cluster-cidr=10.42.0.0/16 --node-external-ip=10.211.55.11 --tls-san=10.211.55.11 ' K3S_TOKEN='8b52b94a2b239e391cfce6a1ce47be78' sh -"
time="2023-01-09T06:14:22Z" level=error msg="error while reading SSH key file: open /root/.ssh/id_rsa: no such file or directory"
time="2023-01-09T06:14:22Z" level=info msg="[native] executing rollback logic..."
time="2023-01-09T06:14:22Z" level=info msg="[native] instances [10-211-55-11 10-211-55-12] will be rollback"
time="2023-01-09T06:14:22Z" level=warning msg="[native] failed to uninstall k3s on master node 10-211-55-11: error while reading SSH key file: open /root/.ssh/id_rsa: no such file or directory"
time="2023-01-09T06:14:22Z" level=warning msg="[native] failed to uninstall k3s on worker node 10-211-55-12: error while reading SSH key file: open /root/.ssh/id_rsa: no such file or directory"
time="2023-01-09T06:14:22Z" level=info msg="[native] successfully executed rollback logic"`

**Comment by orangedeng** [comment]
Which autok3s version did you use? and could you also post the cluster create command in the issue? Thanks!

**Comment by Jason-ZW** [comment]
As there is no follow-up information to supplement, it is temporarily closed, if you have any questions, please reopen.
