### ISSUE TITLE
[BUG]  Restarting the autok3s or refreshing the autok3s ui causes k3d to remain in the stop state

### ISSUE THREAD

**Issue by TangStone** [cnrancher/autok3s#556]
**Describe the bug**
Only the Docker deployed autok3s will restart the autok3s or refresh the autok3s UI, causing the original k3d cluster to remain in the stop state，
**To reproduce**
1. On the ubuntu-18.04 (8c8g) instance, Docker starts the 0.6.0 version of autok3s, and creates the k3d cluster and aliyun cluster through quickstart
```
docker run -itd --restart=unless-stopped --net host -v /var/run/docker.sock:/var/run/docker.sock cnrancher/autok3s:v0.6.0
```
2. Restart autok3s version 0.6.0 or refresh the autok3s UI
```
docker restart <container-id>
```
3. Check the autok3s UI. The original aliyun cluster is running normally, and the k3d cluster is always in the stop state. With the upgraded version, you can successfully create a new k3d cluster

**Screenshots
 - OS: ubuntu20.04 / Docker 20.10.12
 - AutoK3s Version : v0.6.0、v0.6.1

**Comment by JacieChao** [comment]
Cannot reproduce this issue with the following steps:
Scenario 1:
- Running AutoK3s in docker by command `docker run -itd --restart=unless-stopped --net host -v /var/run/docker.sock:/var/run/docker.sock cnrancher/autok3s:v0.6.0`
- Create a K3d cluster with API Port `127.0.0.1:9999` and 1 master node
- Restart AutoK3s and refresh UI. The cluster shows `Active` status and can access the cluster with `autok3s kubectl`
Scenario 2:
- Running AutoK3s in docker by command `docker run -itd --restart=unless-stopped --net host -v /var/run/docker.sock:/var/run/docker.sock cnrancher/autok3s:v0.6.0`
- Create a K3d cluster with API Port `0.0.0.0:0` and 1 master 1 worker node
- Restart AutoK3s and refresh UI. The cluster shows `Active` status and can access the cluster with `autok3s kubectl`
Scenario 3:
- Running AutoK3s in docker by command `docker run -itd --restart=unless-stopped --net host -v /var/run/docker.sock:/var/run/docker.sock cnrancher/autok3s:v0.6.0`
- Create a K3d cluster with API Port `0.0.0.0:0` and 1 master 1 worker node
- Create a K3d cluster with API Port `127.0.0.1:8989` and 1 master node
- Upgrade AutoK3s to v0.7.0 and refresh UI. All clusters shows `Active` status and can access the cluster with `autok3s kubectl`

**Comment by JacieChao** [comment]
Tested with v0.8.0:
- Running AutoK3s in docker by command `docker run -itd --restart=unless-stopped --net host -v /var/run/docker.sock:/var/run/docker.sock cnrancher/autok3s:v0.6.0`
- Create a K3d cluster with API Port 0.0.0.0:0 and 1 master node
- Create a K3d cluster with API Port 127.0.0.1:7777 and 1 master 1 worker node
- Upgrade AutoK3s to v0.8.0 by command `docker run -itd --restart=unless-stopped --net host -v /var/run/docker.sock:/var/run/docker.sock --volumes-from <old-container-id> cnrancher/autok3s:v0.8.0`
- Refresh UI. All K3d cluster shows `Active` status and can access the cluster with `autok3s kubectl`
