### ISSUE TITLE
Modify -`--data-dir` default `/var/lib` path offline image cannot be imported normally

### ISSUE THREAD

**Issue by jinjianming** [cnrancher/autok3s#578]
How to modify the default `/var/lib/ranger/k3s/agent/images/` offline path for k3s

When I deploy, I modify the data path, but the offline image import path remains the same
`/var/lib/rancher/k3s/agent/images/`

--master-extra-args '--data-dir /data/lib/rancher/k3s'  --worker-extra-args '--data-dir /data/lib/rancher/k3s' 

This caused my offline deployment to fail

```
[root@HK-Proxy01 ~]# kubectl get po -A
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
kube-system   coredns-7b5bbc6644-x42cb                  0/1     ContainerCreating   0          7m35s
kube-system   helm-install-traefik-9jsxp                0/1     ContainerCreating   0          7m35s
kube-system   helm-install-traefik-crd-jczkx            0/1     ContainerCreating   0          7m35s
kube-system   local-path-provisioner-687d6d7765-64zsq   0/1     ContainerCreating   0          7m35s
kube-system   metrics-server-667586758d-j9v42           0/1     ContainerCreating   0          7m35s
```

**Comment by jinjianming** [comment]
@orangedeng  hello
When is it expected to release [v0.8.0]， Is there a temporary solution to this issue？

**Comment by orangedeng** [comment]
I think your `/data` path is a mount point for a volume. You can either create a mount point at `/var/lib/rancher/k3s` or create symbol link via `sudo ln -s /data/lib/rancher/k3s /var/lib/rancher/k3s`.

**Comment by orangedeng** [comment]
The feature PR has been merged, you can build your own binary to test it. Closing this issue and feel free to reopen this issue if needed.

**Comment by jinjianming** [comment]
@orangedeng When deleting the cluster in autok3s, the data directory defined by `--data-dir` was not deleted
