### ISSUE TITLE
[Q] Can not find "package-download-source" to change

### ISSUE THREAD

**Issue by jack-liew** [cnrancher/autok3s#579]
Hi:
I found description of doc:
 "如果遇到 Github 站点访问困难的情况，可以通过 autok3s serve 开启UI界面，在 API UI中修改配置 /v1/settings/package-download-source，从 github 改为 aliyunoss，使 autok3s 从 aliyun OSS 分发站点中进行下载。在未来的版本会支持在CLI中修改该配置。"

![image](https://user-images.githubusercontent.com/102201538/232414190-f05a0fbd-c508-43ad-b304-2058c93a76ae.png)

But i can not find "/v1/settings/package-download-source"
---

I have obtained the following four files through other way:
![image](https://user-images.githubusercontent.com/102201538/232416002-a7d1838e-8bb7-41b4-aea1-9b88e283cfff.png)

How should i do next?
---

**Thanks and great work**

**Comment by JacieChao** [comment]
Could you show the response results for API `http://127.0.0.1:8080/v1/settings/package-download-source`? I can get this API response properly with v0.7.0.

**Comment by jack-liew** [comment]
> Could you show the response results for API `http://127.0.0.1:8080/v1/settings/package-download-source`? I can get this API response properly with v0.7.0.

Yes, Ican see the json

**Comment by JacieChao** [comment]
@jack-liew 😄
