### ISSUE TITLE
[Feature Request] Offline installation of helm3

### ISSUE THREAD

**Issue by jinjianming** [cnrancher/autok3s#584]
@orangedeng  在Kubernetes下helm工具作为必不可少的工具之一，K3S中也是如此，希望autok3s支持安装helm，像k3s一样将helm指令放到/usr/local/bin下面提供使用；

**Comment by orangedeng** [comment]
Please provide more information for your feature request

**Comment by orangedeng** [comment]
I think this feature can also fulfill your requirement https://github.com/cnrancher/autok3s/issues/499. And I think the k3s also has helm operator to install charts with CRDs, you can try it first. https://docs.k3s.io/helm

**Comment by JacieChao** [comment]
For now, you can use manifest configuration to install Helm Chart using the `--manifests` parameter. And you can try the example from https://docs.k3s.io/helm

**Comment by JacieChao** [comment]
AutoK3s support enables the helm-dashboard to handle chart installation. Users can prepare for their own helm repo and install charts by helm-dashboard UI. Please feel free to reopen this issue if you have any other feature requests. Close this as complete.
