### ISSUE TITLE
can not deploy kube-explorer when create cluster.

### ISSUE THREAD

**Issue by jack-liew** [cnrancher/autok3s#586]
can not deploy kube-explorer with autok3s when create cluster.

1. choose aliyunoss to download air-gap image.
2. configure ssh, master and node.
3. checked kube-explorer.
4. click [create] cluster, k3s service been deployed to master and node, but The log will prompt somting like "can not deploy Kube-Explorer".
kubectl command can also be used.

 - OS: [ubuntu 22.04]
 - Autok3s: [0.70]

**Comment by JacieChao** [comment]
@jack-liew Could you provide more logs for this issue? Which version of kube-explorer are you using and how to install it?

I tried the following steps and the kube-explorer works as expected.
- Installed AutoK3s 0.7.0 binary on Ubuntu 22.04 using command `curl -sS https://rancher-mirror.rancher.cn/autok3s/install.sh  | sh`
- Install a native cluster with a master and a worker node. 
- Install cluster with airgap package with version v1.25.8+k3s1. 
- Enable kube-explorer when creating cluster.

**Comment by JacieChao** [comment]
@jack-liew The log shows that you don't have the executable `kube-explorer` on your host. Please check if you have `kube-explorer` on your host.

If you are using AutoK3s running in docker, the `kube-explorer` is available in the docker image.
If you are using AutoK3s binary, you can try the command below to install both AutoK3s and kube-explorer.
```
curl -sS https://rancher-mirror.rancher.cn/autok3s/install.sh  | sh
```

**Comment by jack-liew** [comment]
> kube-explorer

I had a wrong thought that kube-explorer was automatically deployed in the master container by Autok3s.

Now I understood. its a web app.

Thank jacie. [手动狗头]
