### ISSUE TITLE
[BUG] Deployment创建时候提示Method PUT not supported

### ISSUE THREAD

**Issue by 195070811** [cnrancher/autok3s#601]
不能正常创建Deployment
![1111](https://github.com/cnrancher/autok3s/assets/17487431/1ec73f38-4c23-4618-873e-6f6d45b1e63e)

**Comment by JacieChao** [comment]
单凭一个截图无法复现问题，请按照issue template提供更详细的信息以便可以定位问题：
1. 使用的AutoK3s版本，kube-explorer版本，如何启动运行AutoK3s
2. 具体的复现步骤以及错误日志

**Comment by JacieChao** [comment]
Please feel free to reopen it if the issue still exists. Close.
