### ISSUE TITLE
[help] cannot create node on Alpine linux 3.17

### ISSUE THREAD

**Issue by jack-liew** [cnrancher/autok3s#602]
**cannot create node on Alpine linux 3.17**

It can create cluster on debian or ubuntu, but alpine.

**Expected behavior**
alpine has no sudo, and apk can not found sudo.

**Environments**
 - OS: alpine linux[v3.17]
 - AutoK3s Version [v0.7.0]

**Comment by orangedeng** [comment]
Refer to https://www.suse.com/suse-k3s/support-matrix/all-supported-versions/k3s-v1-26/

It is a k3s support matrix problem. Although from [k3s docs](https://docs.k3s.io/installation/requirements#operating-systems) says that `K3s is expected to work on most modern Linux systems.`, it also has the support matrix and the alpine isn't in that list. So the autok3s is also not expected to install k3s in alpine linux.

We will look into the possibility to install k3s in alpine but I don't think it is a bug of autok3s.

**Comment by orangedeng** [comment]
I tried to use `curl -sfL https://get.k3s.io | sh -` and succeed to install k3s in alpine 3.17.2. We will improve the install script in autok3s.

**Comment by gedw99** [comment]
thanks @orangedeng

**Comment by jack-liew** [comment]
> I tried to use curl -sfL https://get.k3s.io | sh - and succeed to install k3s in alpine 3.17.2. We will improve the install script in autok3s.

I visited https://docs.rancher.cn/docs/k3s/advanced/_index, it has how to setup k3s on alpine linux, I thought it‘s about create cluster on alpine  by autok3s.
maybe should modify the doc?
---
Thank orangedeng

**Comment by orangedeng** [comment]
> I visited https://docs.rancher.cn/docs/k3s/advanced/_index, it has how to setup k3s on alpine linux, I thought it‘s about create cluster on alpine by autok3s.
maybe should modify the doc?

This issue is the autok3s problem. The install script from autok3s is using `sudo` which the alpine doesn't have. Both the support matrix and community docs are fine.

The support matrix is more about the commercial support. It doesn't affect that `K3s is expected to work on most modern Linux systems.`

I will fix it in v0.9.0

**Comment by orangedeng** [comment]
Resolved in v0.9.0-rc1, already tested autok3s install k3s on Alpine linux with 1 master and 1 worker node via airgap install.
