### ISSUE TITLE
[Feature Request] Support Rancher Manager Add-on options

### ISSUE THREAD

**Issue by JacieChao** [cnrancher/autok3s#605]
As the feature design discussion at https://github.com/cnrancher/autok3s/discussions/606:
 - [x] Add `autok3s add-ons` CLI. Need to support creating add-ons by YAML file and set configurations.
 - [x] Support `--enable` add-ons and set add-on configurations for `autok3s create` CLI.
 - [x] Add add-ons management API.
 - [x] Add default Rancher add-on.
 - [x] Add add-ons management UI page.
 - [x] Support select add-ons for the creating cluster page for each provider.
 - [x] Add documentation for add-on feature

**Comment by ly5156** [comment]
1. add-ons list page
<img width="1386" alt="image" src="https://github.com/cnrancher/autok3s/assets/3406205/cbd21cb8-4638-48b1-aa52-cee09cb10bed">
2. add-ons edit page
<img width="1386" alt="image" src="https://github.com/cnrancher/autok3s/assets/3406205/709b351e-aac9-40e5-909a-47577d3967d9">
3. create add-ons page
<img width="1391" alt="image" src="https://github.com/cnrancher/autok3s/assets/3406205/bc69da3f-45f2-46c4-91aa-9b8e54ec46dc">
4. select add-ons 
<img width="1384" alt="image" src="https://github.com/cnrancher/autok3s/assets/3406205/bedfc06a-b65d-44f4-9014-2b557f71d7c1">

**Comment by orangedeng** [comment]
Test passed with 0.9.0-rc3
