### ISSUE TITLE
[BUG] enbale explorer 失败

### ISSUE THREAD

**Issue by energy162** [cnrancher/autok3s#610]
**Describe the bug**
enbale explorer 失败

**To reproduce**
1. 创建腾讯云集群
2. 点击 enbale explorer
3. 提示错误信息。failed to create tcp listener: listen tcp 198.18.0.46:0: bind: can't assign requested address

**Environments (please complete the following information):**
 - OS: macOS Monterey 12.6.6
 - AutoK3s Version [v0.8.0]

**Additional context**
问题已经解决，做下记录以便遇到类似问题的朋友排查。

我本地修改过localhost指向的ip，将127.0.0.1   localhost记录添加至hosts中便正常了

```
在autok3s UI模式下启动kube-explorer的场景下，中间有个过程是去寻找可用的端口，使用的是 "localhost:0" 这个本地地址
正常情况下，本地的 hosts会将 localhost解析成 127.0.0.1，
由于本地的hosts没有配置，则去了网络上配置的dns服务器查找localhost这个域名对应的地址
```

**Comment by orangedeng** [comment]
I am going to close this issue as it has been resolved.
