### ISSUE TITLE
autok3s join使用离线安装包

### ISSUE THREAD

**Issue by xiaozi789** [cnrancher/autok3s#613]
**Is your feature request related to a problem? Please describe.**
当我用autok3s airgap import一个安装包，然后autok3s create的时候可以很顺利成功，我想问一下我如何能使autok3s join和 autok3s create一样使用--package-name这样的参数就可以将离线的包部署到新的节点上，目前提供的指令来看join不支持--package-name，

**Comment by orangedeng** [comment]
设计上Join是支持airgap安装的，因为在一开始安装集群时，已经选择了airgap package，所以在join时不需要再指定airgap package，直接运行join命令即可

**Comment by orangedeng** [comment]
如果没有更新的话，我先把issue close了
