### ISSUE TITLE
[BUG] k3d provider can't join more than one worker node to a cluster with only a master node

### ISSUE THREAD

**Issue by sunyakun** [cnrancher/autok3s#615]
**Describe the bug**

k3d 集群初次创建时如果只有一个 master 节点，那么使用 autok3s join 命令则最多只能添加一个 worker 节点，当超过一个 worker 节点后再次执行 autok3s join 则会失败

**To reproduce**
1. 使用 autok3s 创建一个只有一个 master 节点的 k3d 集群
```shell
$ autok3s create -p k3d --name test --master 1
```

2. 向 k3d 集群添加一个 worker 节点
```shell
$ autok3s join -p k3d --name test --worker 1
```

3. 继续向集群添加 worker 节点
```shell
$ autok3s join -p k3d --name test --worker 1
```

**Expected behavior**

期望命令全部执行成功，最终 k3d 集群有一个 master 节点和两个 worker 节点

**Screenshots**

![image](https://github.com/cnrancher/autok3s/assets/19233305/94692873-1a95-47f6-9487-963c23c30f2f)

**Environments (please complete the following information):**
 - OS: docker image cnrancher/autok3s:v0.8.0
 - AutoK3s Version {"gitVersion":"v0.8.0","gitCommit":"e4f13c2fb22e6b12859cc9d5f21501409927803c","gitTreeState":"","buildDate":"2023-05-15T08:07:40Z","goVersion":"go1.19.9","compiler":"gc","platform":"linux/amd64"}

**Comment by JacieChao** [comment]
Thanks for the feedback.
When adding the agent node one by one, the K3d agent name is duplicated when stitching the K3d Node name. 

As a workaround, please add or join multiple worker nodes at one time. We will fix this issue in the next version.

**Comment by sunyakun** [comment]
By the way, if the join command fails to execute, autok3s will attempt to perform a rollback, including deleting the kubectl context config. I believe this behavior is unexpected.

**Comment by JacieChao** [comment]
Yes, rollback with failure won't remove the kubectl context config when joining nodes. Will fix this issue too.

**Comment by sunyakun** [comment]
I would be happy to submit a PR to fix this bug. You can assign this issue to me.

**Comment by JacieChao** [comment]
Sure. Thanks
