### ISSUE TITLE
[BUG] helm-dashboard can't open

### ISSUE THREAD

**Issue by orangedeng** [cnrancher/autok3s#630]
**Describe the bug**
Can not open helm dashboard via docker-run autok3s instance

**To reproduce**

1. `docker run -itd --restart=unless-stopped --net=host -v /var/run/docker.sock:/var/run/docker.sock cnrancher/autok3s:v0.9.0-rc2`
2. create a native cluster with 1 node.
3. enable helm-dashboard feature flag.
4. accessing helm dashboard in clusters list page

**Expected behavior**
Jump to helm dashboard page

**Screenshots**
<img width="1675" alt="截屏2023-08-24 16 06 53" src="https://github.com/cnrancher/autok3s/assets/15376837/0edfa42f-bb70-4f1d-820d-4cdab3c8ee6f">

```log
INFO[0000] Helm Dashboard by Komodor, version 1.3.3 (b61adf133f639b8bffd43925b5b4b8230c197a26 @ 2023-06-22T08:59:05Z) 
INFO[0000] User analytics is collected to improve the quality, disable it with --no-analytics 
INFO[0000] Access web UI at: http://localhost:34325/
```

**Environments (please complete the following information):**
 - OS: debian 11
 - AutoK3s Version v0.9.0-rc2

**Additional context**

**Comment by JacieChao** [comment]
As helm-dashboard UI can't support the Base url setting, so we can't use a proxy to redirect requests by AutoK3s server. We changed the bind-address to `0.0.0.0` for docker mode server and users can access the helm-dashboard UI only by running with host-network.

**Comment by orangedeng** [comment]
Test passed with v0.9.0-rc3.
