### ISSUE TITLE
[BUG] 使用k3d provider时出现K3D错误

### ISSUE THREAD

**Issue by putao520** [cnrancher/autok3s#634]
time="2023-08-31T14:50:46Z" level=info msg="[k3d] begin to create cluster xxx..."
time="2023-08-31T14:50:46Z" level=info msg="[k3d] 1 masters and 0 workers will be added"
time="2023-08-31T14:50:46Z" level=info msg="Prep: Network"
time="2023-08-31T14:50:46Z" level=info msg="Re-using existing network 'k3d-xxx' (a2546b88fc9896bc32f842dac4a7546d09255d59f6e8cd5d35afc5405d345650)"
time="2023-08-31T14:50:46Z" level=info msg="Created image volume k3d-xxx-images"
time="2023-08-31T14:50:46Z" level=info msg="Starting new tools node..."
time="2023-08-31T14:50:46Z" level=info msg="Starting Node 'k3d-xxx-tools'"
time="2023-08-31T14:50:47Z" level=info msg="Creating node 'k3d-xxx-server-0'"
time="2023-08-31T14:50:47Z" level=info msg="Creating LoadBalancer 'k3d-xxxserverlb'"
time="2023-08-31T14:50:47Z" level=info msg="Using the k3d-tools node to gather environment information"
time="2023-08-31T14:50:48Z" level=info msg="HostIP: using network gateway 172.18.0.1 address"
time="2023-08-31T14:50:48Z" level=info msg="Starting cluster 'xxx'"
time="2023-08-31T14:50:48Z" level=info msg="Starting servers..."
time="2023-08-31T14:50:48Z" level=info msg="Starting Node 'k3d-xxx-server-0'"
time="2023-08-31T14:50:57Z" level=info msg="All agents already running."
time="2023-08-31T14:50:57Z" level=info msg="Starting helpers..."
time="2023-08-31T14:50:58Z" level=info msg="Starting Node 'k3d-xxx-serverlb'"
time="2023-08-31T14:51:05Z" level=info msg="Injecting records for hostAliases (incl. host.k3d.internal) and for 2 network members into CoreDNS configmap..."
time="2023-08-31T14:51:06Z" level=error msg="[k3d] cluster xxx run failed: Failed Cluster Start: error during post-start cluster preparation: error overwriting contents of /etc/hosts: docker failed to attach to exec process in node 'k3d-xxx-server-0': http: invalid Host header"
time="2023-08-31T14:51:06Z" level=warning msg="[k3d] skip executing rollback logic. This is only used for troubleshooting, the instances and cluster is out of control by AutoK3s. Please check K3s error log and uninstalled manually if needed."

**Comment by JacieChao** [comment]
Please provide more detailed information as the issue template mentions will be more helpful. 
-  What kind of OS are you running for AutoK3s
- AutoK3s version, and how to start it? (using CLI or docker run)
- what is your docker version.
- what is your create args for create K3d cluster.

It seems like a [docker issue](https://github.com/moby/moby/issues/45935) from the log shows.

**Comment by putao520** [comment]
好像是go版本问题导致http: invalid Host header错误

**Comment by D-WadeLv** [comment]
> 好像是go版本问题导致http: invalid Host header错误

I also met the problem, downgrade the autok3s version can soulve it

**Comment by JacieChao** [comment]
@D-WadeLv Which version of AutoK3s are you facing this issue? Could you please provide more detailed information?

**Comment by D-WadeLv** [comment]
> @D-WadeLv Which version of AutoK3s are you facing this issue? Could you please provide more detailed information?
Now I use Autok3s v0.6.0, it works sucessfully.
You can download packages of your OS and wannted version

**Comment by D-WadeLv** [comment]
> I can't help more without any useful information. The k3d provider works fine with AutoK3s v0.9.0 with docker v20.10.12 on MacOS M1 and also works fine on Ubuntu 22.04.

the Autok3s version caused the problem, you could try to downgrade the version to solve it.
Autok3s v0.6.0 download link: https://github.com/cnrancher/autok3s/releases/tag/v0.6.0

**Comment by D-WadeLv** [comment]
> I can't help more without any useful information. The k3d provider works fine with AutoK3s v0.9.0 with docker v20.10.12 on MacOS M1 and also works fine on Ubuntu 22.04.

The version as you say cannot works in my Ubuntu22.04, I want to download AutoK3s v0.6.0 by shell like "curl -sS https://rancher-mirror.rancher.cn/autok3s/install.sh  | INSTALL_AUTOK3S_MIRROR=cn sh", can you tell me how to edit the shell?

**Comment by orangedeng** [comment]
I can reproduce this issue with ubuntu 22.04 and autok3s v0.9.0

**Comment by JacieChao** [comment]
Validate with v0.9.1 Ubuntu 22.04 + docker 24.0.6.
Close as complete.
Please upgrade to v0.9.1 to resolve this issue and feel free to reopen it if the issue still exists.
