### ISSUE TITLE
[Enhancement] Cluster list page should show k3s version

### ISSUE THREAD

**Issue by Jason-ZW** [cnrancher/autok3s#644]
It's better to show k3s/k3d version on cluster list page.

**Comment by JacieChao** [comment]
Tested with v0.9.2-rc1. The cluster list page can show the k3s/k3d version properly.

<img width="1463" alt="image" src="https://github.com/cnrancher/autok3s/assets/23305062/8777566c-021b-4f2e-be79-df522b9db3b0">
