### ISSUE TITLE
[BUG] Cant make HA k3d cluster

### ISSUE THREAD

**Issue by dlbears** [cnrancher/autok3s#672]
**Describe the bug**
Described in the title

**To reproduce**
1. Run this command: "autok3s create --provider k3d --master 3 --name test --worker 0 --api-port 0.0.0.0:0 --image docker.io/rancher/k3s:v1.28.5-k3s1"
2. See the following error message: "FATA[2024-04-26T10:53:27-04:00] [k3d] calling preflight error: need to set `--cluster` or `--datastore` when `--master` number > 1"
3. cant or dont know where to pass --datastore / --cluster in the command to make this work, i've tried to add it to --master-extra-args and at the top of the command but either way it is the same error

**Expected behavior**
Based on the docs for k3d HA cluster should work

**Environments (please complete the following information):**
 - OS: Darwin Latest
 - AutoK3s Version v0.9.2

**Comment by Jason-ZW** [comment]
Hi @dlbears:
Thanks for you feedback. Maybe it's a bug at the [createCheck](https://github.com/cnrancher/autok3s/blob/master/pkg/cluster/base.go#L695) function. We will be check the code and fixed it ASAP.

**Comment by JacieChao** [comment]
Tested with v0.9.3-rc1.
