### ISSUE TITLE
登录页面账号密码支持

### ISSUE THREAD

**Issue by molixiaoge** [cnrancher/autok3s#675]
开启docker 端口就可以直接访问了，没有账号密码的话，用于生产不安全。是否考虑增加账号密码登录功能？

**Comment by orangedeng** [comment]
> 开启docker 端口就可以直接访问了

这里不太理解，能详细描述一下场景吗？

**Comment by Jason-ZW** [comment]
AutoK3s 设计之初是面向研发和测试人员快速部署 K3s/K8s 环境的便捷工具。所以我们更专注于快速拉起 K3s/K8s 环境用于研发和测试这也包括对集群的高级配置和生命周期的简单管理。 @molixiaoge 感谢您的 Feature Request，我们会有计划进行此功能的评估和设计，考虑到 AutoK3s 会被其他工具或者自动化平台以 Cli 方式调用，因此登陆认证并不是仅仅需要考虑上述场景。后续可以关注此 Issue 动态，一旦我们评估并同意采纳此 Feature Request，会有 RFC 设计文档。

**Comment by molixiaoge** [comment]
好的，感谢提供优秀的工具
