### ISSUE TITLE
[BUG] Unable to create aws credentials

### ISSUE THREAD

**Issue by orangedeng** [cnrancher/autok3s#689]
In credentials page, create aws credentials.
![截屏2024-09-20 15 45 48](https://github.com/user-attachments/assets/747597d3-8062-46cf-bc1b-df11d030cf5c)

As described above, backend returns 422 status code and message is `missing credential session-token`

**Comment by ly5156** [comment]
@orangedeng 
用的是哪个版本?
v0.9.2 版本已经添加 session-token 参数

**Comment by orangedeng** [comment]
看来是我UI版本比较老的问题，v0.9.3中已经确认有 session-token 输入字段
